export const PUBLIC_NATIVE_EXPORT_NAMES = [
  'SIGNATURES_ONLY_HINT',
  'minifyContent',
  'applyContentViewMinification',
  'extractSignatures',
  'extractJsSymbols',
  'findInFileReferences',
  'extractGraphFacts',
  'scanGraphFacts',
  'getSupportedJsTsExtensions',
  'getSupportedGraphFactExtensions',
  'getGraphFactCapabilities',
  'getGrammarCapabilities',
  'structuralSearch',
  'structuralSearchDetailed',
  'structuralSearchFiles',
  'structuralSearchFilesDetailed',
  'getSupportedStructuralExtensions',
  'getSemanticBoundaryOffsets',
  'getSupportedSignatureExtensions',
  'jsonToYamlString',
  'SUPPORTED_SIGNATURE_EXTENSIONS',
  'SUPPORTED_GRAPH_FACT_EXTENSIONS',
  'SUPPORTED_STRUCTURAL_EXTENSIONS',
  'parseRipgrepJson',
  'searchRipgrep',
  'validateRipgrepPattern',
  'queryFileSystem',
  'charToByteOffset',
  'byteToCharOffset',
  'byteSliceContent',
  'sliceContent',
  'extractMatchingLines',
  'filterPatch',
  'PatchLineType',
  'NativeLspClient',
  'resolvePosition',
  'resolvePositionFromContent',
  'toUri',
  'fromUri',
  'resolveWorkspaceRootForFile',
  'detectLanguageId',
  'getLanguageServerForFile',
  'isCommandAvailable',
  'safeReadFile',
  'safeReadLineWindow',
  'validateLspServerPath',
  'convertSymbolKind',
  'toLspSymbolKind',
  'sanitizeContent',
  'maskSensitiveData',
] as const;

const NON_FUNCTION_NATIVE_EXPORT_NAMES = new Set<string>([
  'SIGNATURES_ONLY_HINT',
  'SUPPORTED_SIGNATURE_EXTENSIONS',
  'SUPPORTED_GRAPH_FACT_EXTENSIONS',
  'SUPPORTED_STRUCTURAL_EXTENSIONS',
  'PatchLineType',
]);

/** Callable subset derived from the canonical public native export manifest. */
export const PUBLIC_NATIVE_FUNCTION_EXPORT_NAMES =
  PUBLIC_NATIVE_EXPORT_NAMES.filter(
    name => !NON_FUNCTION_NATIVE_EXPORT_NAMES.has(name)
  );
