/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'octocode-minifier-utils.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.android-arm64.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'octocode-minifier-utils.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.android-arm-eabi.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'octocode-minifier-utils.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'octocode-minifier-utils.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'octocode-minifier-utils.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'octocode-minifier-utils.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./octocode-minifier-utils.darwin-universal.node')
      } else {
        nativeBinding = require('@octocodeai/octocode-minifier-utils-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'octocode-minifier-utils.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.darwin-x64.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'octocode-minifier-utils.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.darwin-arm64.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'octocode-minifier-utils.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./octocode-minifier-utils.freebsd-x64.node')
      } else {
        nativeBinding = require('@octocodeai/octocode-minifier-utils-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-x64-musl.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'octocode-minifier-utils.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./octocode-minifier-utils.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'octocode-minifier-utils.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./octocode-minifier-utils.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@octocodeai/octocode-minifier-utils-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { SIGNATURES_ONLY_HINT, getExtension, minifyContentSync, minifyContentResult, applyMinification, applyContentViewMinification, removeComments, minifyConservativeCore, minifyAggressiveCore, minifyJsonCore, minifyJsonReadable, minifyCodeCore, minifyGeneralCore, minifyMarkdownCore, minifyCSSCore, minifyHTMLCore, minifyJavaScriptCore, minifyCSSQuality, minifyHTMLQuality, stripPythonDocstrings, extractSignatures, getSemanticBoundaryOffsets, getSupportedSignatureExtensions, jsonToYamlString, getMINIFY_CONFIG } = nativeBinding

module.exports.SIGNATURES_ONLY_HINT = SIGNATURES_ONLY_HINT
module.exports.getExtension = getExtension
module.exports.minifyContentSync = minifyContentSync
module.exports.minifyContentResult = minifyContentResult
module.exports.applyMinification = applyMinification
module.exports.applyContentViewMinification = applyContentViewMinification
module.exports.removeComments = removeComments
module.exports.minifyConservativeCore = minifyConservativeCore
module.exports.minifyAggressiveCore = minifyAggressiveCore
module.exports.minifyJsonCore = minifyJsonCore
module.exports.minifyJsonReadable = minifyJsonReadable
module.exports.minifyCodeCore = minifyCodeCore
module.exports.minifyGeneralCore = minifyGeneralCore
module.exports.minifyMarkdownCore = minifyMarkdownCore
module.exports.minifyCSSCore = minifyCSSCore
module.exports.minifyHTMLCore = minifyHTMLCore
module.exports.minifyJavaScriptCore = minifyJavaScriptCore
module.exports.minifyCSSQuality = minifyCSSQuality
module.exports.minifyHTMLQuality = minifyHTMLQuality
module.exports.stripPythonDocstrings = stripPythonDocstrings
module.exports.extractSignatures = extractSignatures
module.exports.getSemanticBoundaryOffsets = getSemanticBoundaryOffsets
module.exports.getSupportedSignatureExtensions = getSupportedSignatureExtensions
module.exports.jsonToYamlString = jsonToYamlString
module.exports.getMINIFY_CONFIG = getMINIFY_CONFIG

// ── postbuild additions ──

// Async-compatible drop-in for the TS `minifyContent(content, filePath): Promise<MinifyResult>`.
// Rust runs synchronously; we wrap in Promise.resolve() for drop-in call-site compatibility.
module.exports.minifyContent = function minifyContent(content, filePath) {
  try { return Promise.resolve(module.exports.minifyContentResult(content, filePath)) }
  catch (e) { return Promise.reject(e) }
}

// MINIFY_CONFIG mirrors the TS package shape: { fileTypes: Record<string, { strategy, comments }> }
module.exports.MINIFY_CONFIG = module.exports.getMINIFY_CONFIG()

// SUPPORTED_SIGNATURE_EXTENSIONS — sorted, frozen array (matches TS constant)
module.exports.SUPPORTED_SIGNATURE_EXTENSIONS =
  Object.freeze(module.exports.getSupportedSignatureExtensions().sort())
