/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GetExtensionOptions {
  lowercase?: boolean
  fallback?: string
}
export interface MinifyResult {
  content: string
  failed: boolean
  /** Strategy name or "failed" */
  type: string
  reason?: string
}
export interface FileTypeMinifyConfig {
  strategy: string
  /** CommentPatternGroup | CommentPatternGroup[] */
  comments?: any
}
export interface YamlConversionConfig {
  sortKeys?: boolean
  keysPriority?: Array<string>
}
export const SIGNATURES_ONLY_HINT: string
export declare function getExtension(filePath: string, options?: GetExtensionOptions | undefined | null): string
export declare function minifyContentSync(content: string, filePath: string): string
/**
 * Sync equivalent of TS `minifyContent` — returns MinifyResult.
 * The JS shim wraps this in Promise.resolve() so callers can await it.
 */
export declare function minifyContentResult(content: string, filePath: string): MinifyResult
export declare function applyMinification(content: string, filePath: string): string
export declare function applyContentViewMinification(content: string, filePath: string): string
/** `commentTypes` accepts a single string or array of strings. */
export declare function removeComments(content: string, commentTypes: any): string
export declare function minifyConservativeCore(content: string, config: FileTypeMinifyConfig): string
export declare function minifyAggressiveCore(content: string, config: FileTypeMinifyConfig): string
export declare function minifyJsonCore(content: string): MinifyResult
export declare function minifyJsonReadable(content: string): MinifyResult
export declare function minifyCodeCore(content: string): string
export declare function minifyGeneralCore(content: string): string
export declare function minifyMarkdownCore(content: string): string
export declare function minifyCSSCore(content: string): string
export declare function minifyHTMLCore(content: string): string
export declare function minifyJavaScriptCore(content: string): string
export declare function minifyCSSQuality(content: string): string
export declare function minifyHTMLQuality(content: string): string
export declare function stripPythonDocstrings(content: string): string
export declare function extractSignatures(content: string, filePath: string): string | null
/**
 * Returns all extensions that have signature extraction support
 * (tree-sitter languages + heuristic-covered languages).
 */
export declare function getSupportedSignatureExtensions(): Array<string>
export declare function jsonToYamlString(jsonObject: any, config?: YamlConversionConfig | undefined | null): string
/**
 * Returns the full MINIFY_CONFIG as a JS-compatible object.
 * Shape: `{ fileTypes: Record<string, { strategy: string, comments: string | string[] | null }> }`
 */
export declare function getMINIFY_CONFIG(): any

// ── postbuild additions ──

/**
 * Async drop-in: Promise.resolve() around the synchronous Rust call — it does
 * NOT move work off the event loop. Failures surface as MinifyResult.failed,
 * not rejections.
 */
export declare function minifyContent(content: string, filePath: string): Promise<MinifyResult>
export declare const MINIFY_CONFIG: {
  fileTypes: Record<string, { strategy: string; comments: string | string[] | null }>
}
export declare const SUPPORTED_SIGNATURE_EXTENSIONS: readonly string[]
