// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./octocode-context-utils.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-android-arm64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-android-arm64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./octocode-context-utils.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-android-arm-eabi')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./octocode-context-utils.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-win32-x64-gnu')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./octocode-context-utils.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-win32-x64-msvc')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./octocode-context-utils.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-win32-ia32-msvc')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./octocode-context-utils.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-win32-arm64-msvc')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./octocode-context-utils.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@octocodeai/octocode-context-utils-darwin-universal')
      const bindingPackageVersion = require('@octocodeai/octocode-context-utils-darwin-universal/package.json').version
      if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./octocode-context-utils.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-darwin-x64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-darwin-x64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./octocode-context-utils.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-darwin-arm64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./octocode-context-utils.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-freebsd-x64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./octocode-context-utils.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-freebsd-arm64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./octocode-context-utils.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-x64-musl')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./octocode-context-utils.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-x64-gnu')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./octocode-context-utils.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-arm64-musl')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./octocode-context-utils.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-arm64-gnu')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./octocode-context-utils.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-arm-musleabihf')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./octocode-context-utils.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./octocode-context-utils.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-loong64-musl')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./octocode-context-utils.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-loong64-gnu')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./octocode-context-utils.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-riscv64-musl')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./octocode-context-utils.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@octocodeai/octocode-context-utils-linux-riscv64-gnu')
          const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./octocode-context-utils.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-linux-ppc64-gnu')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./octocode-context-utils.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-linux-s390x-gnu')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./octocode-context-utils.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-openharmony-arm64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./octocode-context-utils.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-openharmony-x64')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./octocode-context-utils.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@octocodeai/octocode-context-utils-openharmony-arm')
        const bindingPackageVersion = require('@octocodeai/octocode-context-utils-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '16.0.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 16.0.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → force WASI fallback even if native loaded
//   'error'                  → force WASI and throw if no WASI binding is found
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' || process.env.NAPI_RS_FORCE_WASI === 'error'

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./octocode-context-utils.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (forceWasi) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding || forceWasi) {
    try {
      wasiBinding = require('@octocodeai/octocode-context-utils-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (forceWasi) {
        if (!wasiBindingError) {
          wasiBindingError = err
        } else {
          wasiBindingError.cause = err
        }
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.applyContentViewMinification = nativeBinding.applyContentViewMinification
module.exports.applyMinification = nativeBinding.applyMinification
module.exports.extractSignatures = nativeBinding.extractSignatures
module.exports.getExtension = nativeBinding.getExtension
module.exports.getMINIFY_CONFIG = nativeBinding.getMINIFY_CONFIG
module.exports.getSemanticBoundaryOffsets = nativeBinding.getSemanticBoundaryOffsets
module.exports.getSupportedSignatureExtensions = nativeBinding.getSupportedSignatureExtensions
module.exports.jsonToYamlString = nativeBinding.jsonToYamlString
module.exports.minifyAggressiveCore = nativeBinding.minifyAggressiveCore
module.exports.minifyCodeCore = nativeBinding.minifyCodeCore
module.exports.minifyConservativeCore = nativeBinding.minifyConservativeCore
module.exports.minifyContentResult = nativeBinding.minifyContentResult
module.exports.minifyContentSync = nativeBinding.minifyContentSync
module.exports.minifyCSSCore = nativeBinding.minifyCSSCore
module.exports.minifyCSSQuality = nativeBinding.minifyCSSQuality
module.exports.minifyGeneralCore = nativeBinding.minifyGeneralCore
module.exports.minifyHTMLCore = nativeBinding.minifyHTMLCore
module.exports.minifyHTMLQuality = nativeBinding.minifyHTMLQuality
module.exports.minifyJavaScriptCore = nativeBinding.minifyJavaScriptCore
module.exports.minifyJsonCore = nativeBinding.minifyJsonCore
module.exports.minifyJsonReadable = nativeBinding.minifyJsonReadable
module.exports.minifyMarkdownCore = nativeBinding.minifyMarkdownCore
module.exports.removeComments = nativeBinding.removeComments
module.exports.SIGNATURES_ONLY_HINT = nativeBinding.SIGNATURES_ONLY_HINT
module.exports.stripPythonDocstrings = nativeBinding.stripPythonDocstrings

// ── postbuild additions ──

// Async-compatible drop-in for the TS `minifyContent(content, filePath): Promise<MinifyResult>`.
// Rust runs synchronously; we wrap in Promise.resolve() for drop-in call-site compatibility.
module.exports.minifyContent = function minifyContent(content, filePath) {
  try { return Promise.resolve(module.exports.minifyContentResult(content, filePath)) }
  catch (e) { return Promise.reject(e) }
}

// MINIFY_CONFIG mirrors the TS package shape: { fileTypes: Record<string, { strategy, comments }> }
module.exports.MINIFY_CONFIG = module.exports.getMINIFY_CONFIG()

// SUPPORTED_SIGNATURE_EXTENSIONS — sorted, frozen array (matches TS constant)
module.exports.SUPPORTED_SIGNATURE_EXTENSIONS =
  Object.freeze(module.exports.getSupportedSignatureExtensions().sort())
