import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { CliCommand, CliSpec, Flag, JsonSchema } from './spec.js';

function zodExpr(flag: Flag): string {
  let expr: string;
  if (flag.kind === 'string') expr = 'z.string()';
  else if (flag.kind === 'integer') expr = 'z.number().int()';
  else if (flag.kind === 'number') expr = 'z.number()';
  else if (flag.kind === 'boolean') expr = 'z.boolean()';
  else if (flag.kind === 'enum' && (flag.enumValues ?? []).every(value => typeof value === 'string') && (flag.enumValues ?? []).length > 0) {
    expr = `z.enum([${(flag.enumValues ?? []).map(value => JSON.stringify(value)).join(', ')}])`;
  } else if (flag.kind === 'array') {
    const item = flag.itemKind === 'integer'
      ? 'z.number().int()'
      : flag.itemKind === 'number'
        ? 'z.number()'
        : flag.itemKind === 'boolean'
          ? 'z.boolean()'
          : 'z.string()';
    expr = `z.array(${item})`;
  } else expr = 'z.unknown()';
  if (flag.description) expr += `.describe(${JSON.stringify(flag.description)})`;
  if (flag.hasDefault) {
    const literal = JSON.stringify(flag.defaultValue);
    if (literal !== undefined) expr += `.default(${literal})`;
  } else if (!flag.required) expr += '.optional()';
  return expr;
}

function zodObject(command: CliCommand): string {
  const fields = command.flags.map(flag => `    ${JSON.stringify(flag.property)}: ${zodExpr(flag)},`);
  return `z.object({\n${fields.join('\n')}\n  })`;
}

function commandLiteral(command: CliCommand, schemaSlot: string | undefined): string {
  const lines = [
    '  defineCommand({',
    `    name: ${JSON.stringify(command.name)},`,
    `    description: ${JSON.stringify(command.description)},`,
    `    source: ${JSON.stringify(command.source)},`,
  ];
  if (schemaSlot) lines.push(`    schema: ${schemaSlot},`);
  if (command.title) lines.push(`    title: ${JSON.stringify(command.title)},`);
  if (command.source === 'mcp') {
    const key = command.mcpName ?? command.name;
    lines.push(`    inputSchema: rawInputSchemas[${JSON.stringify(key)}],`);
  }
  if (command.outputSchema) lines.push(`    outputSchema: ${JSON.stringify(command.outputSchema)},`);
  if (command.annotations) lines.push(`    annotations: ${JSON.stringify(command.annotations)},`);
  if (command.mcpName) lines.push(`    mcpName: ${JSON.stringify(command.mcpName)},`);
  lines.push('    run: async () => {', "      throw new Error('no handler');", '    },', '  }),');
  return lines.join('\n');
}

export function renderTypeScript(spec: CliSpec): string {
  const raw: Record<string, JsonSchema> = {};
  for (const command of spec.commands) {
    if (command.source === 'mcp' && command.inputSchema) {
      raw[command.mcpName ?? command.name] = command.inputSchema;
    }
  }
  const mcp = spec.commands.filter(command => command.source === 'mcp');
  const authored = spec.commands.filter(command => command.source === 'zod');
  const parts = [
    '// Generated by octocode-mcp-cli. Do not edit.',
    "import { z } from 'zod';",
    "import { defineCommand } from 'octocode-mcp-cli';",
    '',
    `export const instructions = ${JSON.stringify(spec.instructions)};`,
    `export const rawInputSchemas = ${JSON.stringify(raw)};`,
    '',
    'export const mcpCommands = [',
    ...mcp.map(command => commandLiteral(command, zodObject(command))),
    '];',
    '',
    'export const authoredCommands = [',
    ...authored.map(command => commandLiteral(command, zodObject(command))),
    '];',
    '',
  ];
  return parts.join('\n');
}

export async function emitTypeScript(spec: CliSpec, filePath: string): Promise<string> {
  const text = renderTypeScript(spec);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, text, 'utf8');
  return text;
}
