//! Tool query, input, and output wire types.
//!
//! Generated by `@octocodeai/config` (`generate:tool-contract`) in the same run
//! as the embedded contract (build.rs refuses a mismatched pair), so Rust never
//! hand-declares a tool wire shape. Regenerate there; never edit.
#![allow(
    dead_code,
    clippy::all,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    missing_docs
)]

include!("../../../../../octocode-config/contract/tool_types.rs");

