//! Tool query, input, and output wire types.
//!
//! Generated by `@octocodeai/config` (`generate:tool-contract`) in the same run
//! as the embedded contract (build.rs refuses a mismatched pair), so Rust never
//! hand-declares a tool wire shape. Regenerate there; never edit.
#![allow(
    dead_code,
    clippy::all,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    missing_docs
)]

include!("../../../../../octocode-config/contract/tool_types.rs");

#[cfg(test)]
mod tests {
    #[test]
    fn generated_types_match_the_embedded_contract() {
        assert_eq!(
            super::TOOL_TYPES_CONTRACT_FINGERPRINT,
            crate::contracts::generated::CONTRACT_FINGERPRINT,
            "run `yarn workspace @octocodeai/config generate:tool-contract`"
        );
    }
}
