use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct SharedConstants {
    #[serde(rename = "_comment")]
    _comment: Option<String>,
    config_schema_version: i64,
    config_file_name: String,
    runtime_surfaces: Vec<String>,
    runtime_surface_default: String,
    env_token_vars: Vec<String>,
    protected_keys: Vec<String>,
    config_source_env_keys: Vec<String>,
    validation_bounds: BTreeMap<String, u64>,
}

fn write_string_array(
    output: &mut String,
    name: &str,
    values: &[String],
) -> Result<(), std::fmt::Error> {
    writeln!(output, "pub const {name}: [&str; {}] = [", values.len())?;
    for value in values {
        writeln!(output, "    {value:?},")?;
    }
    writeln!(output, "];\n")
}

fn to_screaming_snake(value: &str) -> String {
    let characters = value.chars().collect::<Vec<_>>();
    let mut output = String::with_capacity(value.len());
    for (index, character) in characters.iter().copied().enumerate() {
        let previous = index.checked_sub(1).and_then(|i| characters.get(i));
        let next = characters.get(index + 1);
        let starts_word = character.is_ascii_uppercase()
            && previous.is_some_and(|value| {
                value.is_ascii_lowercase()
                    || value.is_ascii_digit()
                    || (value.is_ascii_uppercase()
                        && next.is_some_and(|next| next.is_ascii_lowercase()))
            });
        if starts_word {
            output.push('_');
        }
        output.push(character.to_ascii_uppercase());
    }
    output
}

fn rust_enum_variant(value: &str) -> Result<String, Box<dyn Error>> {
    if value.is_empty()
        || !value
            .chars()
            .all(|character| character.is_ascii_alphanumeric())
    {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("invalid runtime surface {value:?}"),
        )
        .into());
    }

    let mut characters = value.chars();
    let first = characters.next().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("invalid empty runtime surface {value:?}"),
        )
    })?;
    Ok(format!(
        "{}{}",
        first.to_ascii_uppercase(),
        characters.as_str()
    ))
}

fn render(constants: &SharedConstants) -> Result<String, Box<dyn Error>> {
    let mut output = String::from(
        "// @generated by crates/runtime/build.rs from packages/octocode-config/shared-constants.json.\n\
         // Do not edit.\n\n",
    );

    writeln!(
        output,
        "pub const CONFIG_SCHEMA_VERSION: i64 = {};",
        constants.config_schema_version
    )?;
    writeln!(
        output,
        "pub const CONFIG_FILE_NAME: &str = {:?};\n",
        constants.config_file_name
    )?;

    writeln!(
        output,
        "#[derive(Clone, Copy, Debug, Default, Eq, PartialEq, serde::Serialize, serde::Deserialize)]"
    )?;
    writeln!(output, "#[serde(rename_all = \"lowercase\")]")?;
    writeln!(output, "pub enum RuntimeSurface {{")?;
    for surface in &constants.runtime_surfaces {
        if surface == &constants.runtime_surface_default {
            writeln!(output, "    #[default]")?;
        }
        writeln!(output, "    {},", rust_enum_variant(surface)?)?;
    }
    writeln!(output, "}}\n")?;

    write_string_array(&mut output, "ENV_TOKEN_VARS", &constants.env_token_vars)?;
    write_string_array(&mut output, "PROTECTED_KEYS", &constants.protected_keys)?;
    write_string_array(
        &mut output,
        "CONFIG_SOURCE_ENV_KEYS",
        &constants.config_source_env_keys,
    )?;

    for (name, value) in &constants.validation_bounds {
        writeln!(
            output,
            "pub const {}: f64 = {value}.0;",
            to_screaming_snake(name)
        )?;
    }

    Ok(output)
}

fn shared_constants_path(manifest_dir: &Path) -> PathBuf {
    manifest_dir.join("../../../../packages/octocode-config/shared-constants.json")
}

fn generate_shared_constants() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let source_path = shared_constants_path(&manifest_dir);
    println!("cargo:rerun-if-changed={}", source_path.display());

    let source = fs::read_to_string(&source_path)?;
    let constants: SharedConstants = serde_json::from_str(&source)?;
    let output_path = PathBuf::from(env::var("OUT_DIR")?).join("shared_constants.rs");
    fs::write(output_path, render(&constants)?)?;
    Ok(())
}

fn main() -> Result<(), Box<dyn Error>> {
    generate_shared_constants()?;

    #[cfg(feature = "napi-addon")]
    napi_build::setup();

    Ok(())
}
