import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { sharedConstantsSchema } from './shared-constants-schema.ts';

const inputPath = fileURLToPath(new URL('../shared-constants.json', import.meta.url));
const outputPath = fileURLToPath(
  new URL('../src/config/sharedConstants.generated.ts', import.meta.url)
);

function toScreamingSnake(value: string): string {
  return value
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toUpperCase();
}

function render(constants: ReturnType<typeof sharedConstantsSchema.parse>): string {
  const values = {
    configSchemaVersion: constants.configSchemaVersion,
    configFileName: constants.configFileName,
    runtimeSurfaces: constants.runtimeSurfaces,
    runtimeSurfaceDefault: constants.runtimeSurfaceDefault,
    outputFormats: constants.outputFormats,
    storageModes: constants.storageModes,
    defaultValues: constants.defaultValues,
    envTokenVars: constants.envTokenVars,
    protectedKeys: constants.protectedKeys,
    configSourceEnvKeys: constants.configSourceEnvKeys,
    validationBounds: constants.validationBounds,
  };

  const defaultExports = Object.keys(values.defaultValues)
    .map(
      key => `export const DEFAULT_${toScreamingSnake(key)} = DEFAULT_VALUES.${key};`
    )
    .join('\n');
  const boundExports = Object.keys(values.validationBounds)
    .map(
      key =>
        `export const ${toScreamingSnake(key)} = VALIDATION_BOUNDS.${key};`
    )
    .join('\n');

  return `// @generated by scripts/generate-shared-constants.ts from shared-constants.json.
// Do not edit; run \`yarn workspace @octocodeai/config generate:shared-constants\`.

export const SHARED_CONSTANTS = ${JSON.stringify(values, null, 2)} as const;

export const CONFIG_SCHEMA_VERSION = SHARED_CONSTANTS.configSchemaVersion;
export const CONFIG_FILE_NAME = SHARED_CONSTANTS.configFileName;
export const RUNTIME_SURFACES = SHARED_CONSTANTS.runtimeSurfaces;
export type RuntimeSurface = (typeof RUNTIME_SURFACES)[number];
export const DEFAULT_RUNTIME_SURFACE: RuntimeSurface = SHARED_CONSTANTS.runtimeSurfaceDefault;
export const OUTPUT_FORMATS = SHARED_CONSTANTS.outputFormats;
export type OutputFormat = (typeof OUTPUT_FORMATS)[number];
export const STORAGE_MODES = SHARED_CONSTANTS.storageModes;
export type StorageMode = (typeof STORAGE_MODES)[number];
export const DEFAULT_VALUES = SHARED_CONSTANTS.defaultValues;
${defaultExports}
export const ENV_TOKEN_VARS = SHARED_CONSTANTS.envTokenVars;
export type EnvTokenVar = (typeof ENV_TOKEN_VARS)[number];
export const PROTECTED_KEY_NAMES = SHARED_CONSTANTS.protectedKeys;
export const CONFIG_SOURCE_ENV_KEYS = SHARED_CONSTANTS.configSourceEnvKeys;
export type ConfigSourceEnvKey = (typeof CONFIG_SOURCE_ENV_KEYS)[number];
export const VALIDATION_BOUNDS = SHARED_CONSTANTS.validationBounds;
${boundExports}
`;
}

async function main(): Promise<void> {
  const raw = JSON.parse(await readFile(inputPath, 'utf8')) as unknown;
  const output = render(sharedConstantsSchema.parse(raw));

  if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== output) {
      throw new Error(
        'Generated shared constants are stale. Run: yarn workspace @octocodeai/config generate:shared-constants'
      );
    }
    return;
  }

  await writeFile(outputPath, output);
}

await main();
