//! Replays the golden parity fixtures generated by the TS suite
//! (`packages/octocode-skill-installer/tests/parity.golden.test.ts`).
//! Every fixture is materialized into a temp root, run through the native
//! installer, normalized identically, and compared field-for-field against
//! the recorded result and filesystem tree. Green here is the R6 gate that
//! authorizes retiring the TS implementation.

use super::{InstallBundledSkillsOptions, install_bundled_skills};
use serde_json::{Value, json};
use std::fs;
use std::path::{Path, PathBuf};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../../octocode-skill-installer/tests/fixtures/parity")
}

fn temp_root(tag: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "octocode-skill-parity-{tag}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("test fixture operation should succeed")
            .as_nanos()
    ));
    fs::create_dir_all(&root).expect("test fixture operation should succeed");
    // macOS: /var → /private/var; fixtures compare lexical paths, so anchor
    // at the canonicalized root to keep <ROOT> substitution exact.
    root.canonicalize()
        .expect("test fixture operation should succeed")
}

fn substitute(value: &Value, from: &str, to: &str) -> Value {
    match value {
        Value::String(text) => Value::String(text.replace(from, to)),
        Value::Array(items) => Value::Array(
            items
                .iter()
                .map(|item| substitute(item, from, to))
                .collect(),
        ),
        Value::Object(map) => Value::Object(
            map.iter()
                .map(|(key, item)| (key.clone(), substitute(item, from, to)))
                .collect(),
        ),
        other => other.clone(),
    }
}

fn materialize_setup(root: &Path, setup: &Value) {
    for entry in setup.as_array().into_iter().flatten() {
        let dir = entry["dir"]
            .as_str()
            .expect("setup dir")
            .replace("<ROOT>", &root.to_string_lossy());
        let marker = entry["marker"].as_str().expect("setup marker");
        fs::create_dir_all(Path::new(&dir).join("references"))
            .expect("test fixture operation should succeed");
        fs::write(
            Path::new(&dir).join("SKILL.md"),
            format!("# Fixture skill ({marker})\n"),
        )
        .expect("test fixture operation should succeed");
        fs::write(
            Path::new(&dir).join("references/guide.md"),
            format!("{marker} guide\n"),
        )
        .expect("test fixture operation should succeed");
    }
}

fn snapshot_tree(root: &Path) -> Value {
    fn walk(root: &Path, dir: &Path, out: &mut Vec<Value>) {
        let mut names: Vec<_> = fs::read_dir(dir)
            .expect("test fixture operation should succeed")
            .filter_map(Result::ok)
            .map(|entry| entry.file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        for name in names {
            let path = dir.join(&name);
            let rel = path
                .strip_prefix(root)
                .expect("test fixture operation should succeed")
                .to_string_lossy()
                .replace('\\', "/");
            let meta = fs::symlink_metadata(&path).expect("test fixture operation should succeed");
            if meta.file_type().is_symlink() {
                let target = fs::read_link(&path)
                    .expect("test fixture operation should succeed")
                    .to_string_lossy()
                    .replace(&*root.to_string_lossy(), "<ROOT>");
                out.push(json!({"path": rel, "kind": "symlink", "target": target}));
            } else if meta.is_dir() {
                out.push(json!({"path": rel, "kind": "dir"}));
                walk(root, &path, out);
            } else {
                let content =
                    fs::read_to_string(&path).expect("test fixture operation should succeed");
                out.push(json!({"path": rel, "kind": "file", "content": content}));
            }
        }
    }
    let mut entries = Vec::new();
    walk(root, root, &mut entries);
    entries.sort_by(|a, b| a["path"].as_str().cmp(&b["path"].as_str()));
    Value::Array(entries)
}

#[test]
fn native_installer_reproduces_every_ts_golden_fixture() {
    let dir = fixtures_dir();
    let mut names: Vec<_> = fs::read_dir(&dir)
        .unwrap_or_else(|_| panic!("parity fixtures missing at {}", dir.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".json"))
        .collect();
    names.sort();
    assert!(!names.is_empty(), "no parity fixtures found");
    for name in names {
        let fixture: Value = serde_json::from_str(
            &fs::read_to_string(dir.join(&name)).expect("test fixture operation should succeed"),
        )
        .expect("test fixture operation should succeed");
        let root = temp_root(name.trim_end_matches(".json"));
        let root_str = root.to_string_lossy().into_owned();
        materialize_setup(&root, &fixture["setup"]);

        let runs = fixture["runs"].as_array().expect("runs array");
        let mut results = Vec::new();
        for run in runs {
            let concrete = substitute(run, "<ROOT>", &root_str);
            let options: InstallBundledSkillsOptions =
                serde_json::from_value(concrete).expect("options deserialize");
            let result =
                serde_json::to_value(install_bundled_skills(&options)).expect("result serialize");
            results.push(substitute(&result, &root_str, "<ROOT>"));
        }
        let produced = if results.len() == 1 {
            results.remove(0)
        } else {
            Value::Array(results)
        };
        assert_eq!(
            produced, fixture["result"],
            "result parity failed for fixture {name}"
        );
        assert_eq!(
            snapshot_tree(&root),
            fixture["tree"],
            "tree parity failed for fixture {name}"
        );
        let _ = fs::remove_dir_all(&root);
    }
}
