import { formatDuration } from '../shared/format.js';
import { sanitizeTerminalText } from '../shared/sanitize.js';
import { priorityName, STATES, type BacklogStore, type Item, type Note, type State } from './store.js';

export const STATE_TITLE: Record<State, string> = { ongoing: 'Ongoing', todo: 'Todo', backlog: 'Backlog (triage)', done: 'Done' };
/** Board and export order: the flow an item follows, so the board's ←/→ step up/down the sections as drawn. */
export const BOARD_ORDER: readonly State[] = STATES;


/** Who holds an item, from the reader's side: `(you)`, `(parent)` (a subagent's parent), `(@main-1a2b)`, or nothing. */
export function holder(item: Item, self?: string, parents?: ReadonlySet<string>): string {
  if (!item.assignee || item.state !== 'ongoing') return '';
  if (item.assignee === self) return ' (you)';
  return parents?.has(item.assignee) ? ' (parent)' : ` (@${sanitizeTerminalText(item.assignee)})`;
}

/** `B12 [ongoing p1] Title #tag (you)` */
export function itemLine(item: Item, self?: string, parents?: ReadonlySet<string>): string {
  const tags = item.tags.map((tag) => ` #${tag}`).join('');
  return `${item.ref} [${item.state} ${priorityName(item.priority)}] ${sanitizeTerminalText(item.title)}${tags}${holder(item, self, parents)}`;
}

const ago = (at: number, now: number) => `${formatDuration(Math.max(0, now - at))} ago`;

/** Who wrote a note or holds an item, from the reader's side: `you`, `your parent`, or the id. */
const who = (id: string, self?: string, parents?: ReadonlySet<string>) => (id === self ? 'you' : parents?.has(id) ? 'your parent' : sanitizeTerminalText(id));

function noteLine(note: Note, now: number, self?: string, parents?: ReadonlySet<string>): string {
  return `- ${ago(note.at, now)} ${who(note.author, self, parents)}: ${sanitizeTerminalText(note.text)}`;
}

interface DetailOptions {
  self?: string;
  /** A subagent's parent sessions, shown as `(parent)`. */
  parents?: ReadonlySet<string>;
  /** Show the version (the board uses it for stale-edit checks; the tool has no use for it). */
  version?: boolean;
}

/** The whole item: header, metadata, body and its last notes. */
export function itemDetail(item: Item, notes: Note[], totalNotes: number, now: number, options: DetailOptions = {}): string {
  const { self, parents } = options;
  const meta = [
    `created ${ago(item.createdAt, now)} by ${sanitizeTerminalText(item.createdBy)}`,
    `updated ${ago(item.updatedAt, now)}`,
    item.doneAt ? `done ${ago(item.doneAt, now)}` : '',
    item.assignee ? `assignee ${who(item.assignee, self, parents)}` : '',
    options.version ? `version ${item.version}` : '',
  ].filter(Boolean);
  const lines = [itemLine(item, self, parents), meta.join(' · ')];
  if (item.body) lines.push('', sanitizeTerminalText(item.body));
  if (notes.length > 0) {
    lines.push('', totalNotes > notes.length ? `Notes (last ${notes.length} of ${totalNotes}):` : 'Notes:', ...notes.map((note) => noteLine(note, now, self, parents)));
  }
  return lines.join('\n');
}

/** Every item grouped by state, for a headless `/octocode backlog`. */
export function boardText(store: BacklogStore, self?: string): string {
  const { items } = store.list();
  if (items.length === 0) return 'The backlog is empty. Add an item: /backlog add <title>';
  const sections = BOARD_ORDER.flatMap((state) => {
    const rows = items.filter((item) => item.state === state);
    return rows.length === 0 ? [] : [`${STATE_TITLE[state]} (${rows.length})`, ...rows.map((item) => `  ${itemLine(item, self)}`)];
  });
  return sections.join('\n');
}

/** Footer counts: `▶1 ☐4 ⧗2` (ongoing, todo, awaiting triage); empty when there is nothing open. */
export function countsText(counts: Record<State, number>): string {
  const parts = [counts.ongoing ? `▶${counts.ongoing}` : '', counts.todo ? `☐${counts.todo}` : '', counts.backlog ? `⧗${counts.backlog}` : ''].filter(Boolean);
  return parts.length ? `backlog ${parts.join(' ')}` : '';
}

/** Markdown snapshot of the whole board with every note, for `<repo>/.octocode/backlog.md`. Nothing reads it back. */
export function exportMarkdown(store: BacklogStore, repoName: string, now: number): string {
  const { items } = store.list();
  const lines = [
    `<!-- Generated by Octocode (/backlog export) at ${new Date(now).toISOString()}. A snapshot: edits here are not read back. -->`,
    `# Backlog — ${sanitizeTerminalText(repoName)}`,
    '',
  ];
  if (items.length === 0) lines.push('_Empty._', '');
  for (const state of BOARD_ORDER) {
    const rows = items.filter((item) => item.state === state);
    if (rows.length === 0) continue;
    lines.push(`## ${STATE_TITLE[state]} (${rows.length})`, '');
    for (const item of rows) {
      const tags = item.tags.map((tag) => ` #${tag}`).join('');
      const who = item.assignee ? ` — ${sanitizeTerminalText(item.assignee)}` : '';
      lines.push(`- **${item.ref}** [${priorityName(item.priority)}] ${sanitizeTerminalText(item.title)}${tags}${who}`);
      for (const line of item.body ? sanitizeTerminalText(item.body).split('\n') : []) lines.push(`  ${line}`.trimEnd());
      for (const note of store.notes(item, -1)) lines.push(`  - ${new Date(note.at).toISOString().slice(0, 16).replace('T', ' ')} ${sanitizeTerminalText(note.author)}: ${sanitizeTerminalText(note.text).replace(/\n/g, ' ')}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export const isState = (word: string): word is State => (STATES as readonly string[]).includes(word);
