// In-repo hub for the tool-contract schema surface. Zod schemas are authored in
// @octocodeai/octocode-core and re-exported here; tool input/output TypeScript
// types are generated by this package (scripts/generate-tool-contract.ts) from the
// same contract that native's Rust types come from. Every Octocode surface
// imports contracts and types from "@octocodeai/config/schema".
export * from "@octocodeai/octocode-core/schema";
export * from "./toolTypes.generated.js";
