import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

export const TYPIFY_VERSION = '0.8.0';

/** The header pins the bundle digest, so staleness is checkable without cargo. */
export const rustHeader = (fingerprint: string, schemaSha256: string): string =>
  `// @generated by @octocodeai/config scripts/generate-tool-contract.ts (cargo-typify ${TYPIFY_VERSION}); do not edit.
// Source: @octocodeai/octocode-core Zod contract ${fingerprint}.
pub const TOOL_TYPES_CONTRACT_FINGERPRINT: &str = ${JSON.stringify(fingerprint)};
pub const TOOL_TYPES_SCHEMA_SHA256: &str = ${JSON.stringify(schemaSha256)};
`;

function requireTypify(): void {
  let version = '';
  try {
    version = execFileSync('cargo', ['typify', '--version'], { encoding: 'utf8' });
  } catch {
    throw new Error(`cargo-typify is required: cargo install cargo-typify --version ${TYPIFY_VERSION} --locked`);
  }
  if (!version.includes(TYPIFY_VERSION)) {
    throw new Error(`cargo-typify ${TYPIFY_VERSION} is required (found ${version.trim()}).`);
  }
}

export function renderRust(header: string, bundleJson: string): string {
  requireTypify();
  const scratch = mkdtempSync(join(tmpdir(), 'octocode-tool-types-'));
  try {
    const input = join(scratch, 'tool-types.schema.json');
    const output = join(scratch, 'tool_types.rs');
    writeFileSync(input, bundleJson);
    execFileSync(
      'cargo',
      [
        'typify',
        '--no-builder',
        '--additional-derive',
        'PartialEq',
        // Deterministic iteration: rule objects feed snapshot digests.
        '--map-type',
        '::std::collections::BTreeMap',
        input,
        '-o',
        output,
      ],
      { stdio: ['ignore', 'ignore', 'pipe'] }
    );
    // Inner attributes cannot survive `include!`; the native wrapper module
    // carries the equivalent `#[allow]`s.
    const generated = readFileSync(output, 'utf8')
      .split('\n')
      .filter((line) => !line.startsWith('#![') && !line.startsWith('//!'))
      .join('\n')
      .trim();
    // Validated string newtypes format like the `String` they wrap.
    const display = [...generated.matchAll(/^pub struct (\w+)\(::std::string::String\);$/gm)]
      .map(
        ([, name]) => `impl ::std::fmt::Display for ${name} {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        f.write_str(&self.0)
    }
}`
      )
      .join('\n');
    return `${header}\n${generated}\n${display}\n`;
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}
