import { compile } from 'json-schema-to-typescript';
import type { JsonObject } from './bundle.ts';

const TOOL_TYPE = /(?:Query|Input|Output)$/;

export async function renderTypeScript(fingerprint: string, bundle: JsonObject): Promise<string> {
  const toolTypes = Object.keys(bundle.$defs as JsonObject).filter((name) => TOOL_TYPE.test(name));
  // A root that references every tool type makes the compiler declare each
  // one (and everything it references) under its own name.
  const root = {
    ...bundle,
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(toolTypes.map((name) => [name, { $ref: `#/$defs/${name}` }])),
  };
  const body = await compile(root as never, 'OctocodeToolTypes', {
    bannerComment: '',
    additionalProperties: false,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    // Cardinality stays a runtime check; tuple expansion of maxItems:25
    // would emit every length as its own union member.
    ignoreMinAndMaxItems: true,
    format: false,
    strictIndexSignatures: true,
    unreachableDefinitions: true,
  });
  const tools = [...new Set(toolTypes.map((name) => name.replace(TOOL_TYPE, '')))];
  const map = (suffix: string): string =>
    tools.map((tool) => `  ${tool.charAt(0).toLowerCase()}${tool.slice(1)}: ${tool}${suffix};`).join('\n');
  const declarations = body
    .replace(/^export interface OctocodeToolTypes \{[\s\S]*?\n\}\n/m, '')
    .trim()
    .replace(/[ \t]+$/gm, '');
  return `// @generated by @octocodeai/config scripts/generate-tool-contract.ts; do not edit.
// Source: @octocodeai/octocode-core Zod contract ${fingerprint}.
/* eslint-disable */

export const TOOL_TYPES_CONTRACT_FINGERPRINT = ${JSON.stringify(fingerprint)};

${declarations}

/** One validated query row, keyed by tool name. */
export interface ToolQueryMap {
${map('Query')}
}
/** Bulk input envelope accepted by each tool, keyed by tool name. */
export interface ToolInputMap {
${map('Input')}
}
/** Structured output envelope returned by each tool, keyed by tool name. */
export interface ToolOutputMap {
${map('Output')}
}
export type ToolTypeName = keyof ToolQueryMap;
export type ToolQuery<N extends ToolTypeName> = ToolQueryMap[N];
export type ToolInput<N extends ToolTypeName> = ToolInputMap[N];
export type ToolOutput<N extends ToolTypeName> = ToolOutputMap[N];
`;
}
