/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class NativeLspClient {
  constructor(config: JsLanguageServerConfig)
  start(): Promise<void>
  stop(): Promise<void>
  /**
   * Wait for the server to finish any post-`initialized` indexing, returning
   * a readiness descriptor so JS can tell a confirmed-idle server apart from
   * one that never reported progress or is still busy. The returned string
   * is one of `"progressIdle"`, `"settledFallback"`, or `"timeout"`.
   */
  waitForReady(timeoutMs?: number | undefined | null): Promise<string>
  /**
   * `false` if the client was never started/already stopped, or if its
   * connection's read loop has observed the server process close (crash).
   * Lets the JS client pool evict a stale pooled entry at the next
   * `acquire()` instead of returning a client whose requests will just
   * fail until the idle timer eventually reaps it.
   */
  isAlive(): Promise<boolean>
  hasCapability(capability: string): boolean
  /**
   * The `positionEncoding` the server selected at initialize time, if any.
   * `None` means the server omitted it (implying the spec default, utf-16) or
   * the client has not started yet. octocode advertises utf-16 only, so a
   * value other than `Some("utf-16")` indicates a non-conformant server.
   */
  positionEncoding(): string | null
  getReadiness(): string | null
  getRecentStderr(): Array<string>
  /**
   * Sync a document's in-memory content to the server, honoring the LSP
   * document lifecycle: the FIRST sync of a URI sends `textDocument/didOpen`
   * (version 1); every subsequent sync sends `textDocument/didChange` with an
   * incremented version and a full-document content change. Re-sending
   * `didOpen` (as before) is ignored or rejected by many servers and can make
   * changed content resolve against the stale original.
   */
  openDocument(filePath: string, content: string): Promise<void>
  /**
   * Close a previously opened document (`textDocument/didClose`) and forget
   * its version, so a later `open_document` starts a fresh `didOpen`.
   */
  closeDocument(filePath: string): Promise<void>
  getDefinition(filePath: string, line: number, character: number): Promise<Array<JsCodeSnippet>>
  getReferences(filePath: string, line: number, character: number, includeDeclaration?: boolean | undefined | null): Promise<Array<JsCodeSnippet>>
  getHover(filePath: string, line: number, character: number): Promise<any>
  getTypeDefinition(filePath: string, line: number, character: number): Promise<Array<JsCodeSnippet>>
  getImplementation(filePath: string, line: number, character: number): Promise<Array<JsCodeSnippet>>
  getDocumentSymbols(filePath: string): Promise<any>
  prepareCallHierarchy(filePath: string, line: number, character: number): Promise<any>
  incomingCalls(item: any): Promise<any>
  outgoingCalls(item: any): Promise<any>
  /**
   * Project-wide fuzzy symbol search — `workspace/symbol`.
   * Returns `WorkspaceSymbol[] | SymbolInformation[]` (raw JSON).
   * `query` is the fuzzy name string; empty string returns all symbols.
   */
  workspaceSymbol(query: string): Promise<any>
  /**
   * Prepare a type-hierarchy item at a given position — `textDocument/prepareTypeHierarchy`.
   * Returns `TypeHierarchyItem[] | null` (raw JSON).
   */
  prepareTypeHierarchy(filePath: string, line: number, character: number): Promise<any>
  /**
   * Retrieve supertypes (base classes / implemented interfaces) — `typeHierarchy/supertypes`.
   * `item` is a `TypeHierarchyItem` previously returned by `prepareTypeHierarchy`.
   */
  typeHierarchySupertypes(item: any): Promise<any>
  /**
   * Retrieve subtypes (subclasses / implementors) — `typeHierarchy/subtypes`.
   * `item` is a `TypeHierarchyItem` previously returned by `prepareTypeHierarchy`.
   */
  typeHierarchySubtypes(item: any): Promise<any>
  /**
   * Pull diagnostics for a single file — `textDocument/diagnostic` (LSP 3.17+).
   * Returns `DocumentDiagnosticReport` with `kind: "full"|"unchanged"` and `items: Diagnostic[]`.
   * Prefer pull diagnostics over push (`publishDiagnostics`) for agent/CLI use: you control
   * *when* to request them and avoid a notification firehose.
   */
  getDiagnostics(filePath: string): Promise<any>
  /**
   * Return the latest bounded `textDocument/publishDiagnostics` payload for
   * a file, waiting briefly when the server has not published one yet.
   */
  getPushDiagnostics(filePath: string, timeoutMs?: number | undefined | null): Promise<any | null>
}

export declare function acquirePooledLspClient(config: JsLanguageServerConfig): Promise<NativeLspClient | null>

/**
 * Agent-readable "standard" view: strips comments and blank-line noise while
 * preserving indentation and code shape. Capped at 1MB; panic-contained.
 */
export declare function applyContentViewMinification(content: string, filePath: string): string

export declare function buildIndex(options: IndexBuildRequest): Promise<unknown>

export interface ByteRange {
  /** Zero-based UTF-8 byte offset. */
  start: number
  /** Exclusive UTF-8 byte end offset. */
  end: number
}

/** Extract a byte-range substring from `content`. */
export declare function byteSliceContent(content: string, byteStart: number, byteEnd: number): string

/**
 * JavaScript UTF-16 code-unit offset for `byte_offset` bytes into `content`.
 * Zero-allocation — no `Buffer.from()` needed.
 */
export declare function byteToCharOffset(content: string, byteOffset: number): number

/**
 * Number of UTF-8 bytes up to (not including) the `char_index`-th JavaScript
 * UTF-16 code unit in `content`. Zero-allocation — no `Buffer.from()` needed.
 */
export declare function charToByteOffset(content: string, charIndex: number): number

export declare function clearPooledLspClients(): Promise<void>

export declare function configureLspClientPool(idleTimeoutMs: number, maxEntries: number): Promise<void>

/** Convert an LSP `SymbolKind` numeric code to a human-readable string tag. */
export declare function convertSymbolKind(kind?: number | undefined | null): string

/** Return the LSP language identifier for the file at `file_path`. */
export declare function detectLanguageId(filePath: string): string | null

/**
 * Native graph facts as JSON.
 *
 * Uses the richer OXC JS/TS graph extractor when available, then falls back to
 * generic tree-sitter graph facts for other source languages. Syntax-level
 * only: declarations, imports, exports, containment, and direct call edges.
 * Cross-file identity and type-aware proof remain LSP work.
 */
export declare function extractGraphFacts(content: string, filePath: string): string | null

/**
 * Native JS/TS document symbols (server-free) as a JSON `DocumentSymbol[]`.
 *
 * Parses ECMAScript/TypeScript *syntax* with `oxc_parser` and walks
 * declarations into the LSP `DocumentSymbol` shape (nested, numeric
 * `SymbolKind`, 0-based UTF-16 ranges). **No type inference** — in-file
 * scope/binding accuracy only; type-aware outlines still require a language
 * server. Only `ts/tsx/js/jsx/mjs/cjs/mts/cts` are handled.
 *
 * Returns `null` for non-JS/TS files, oversized content, a hard parse failure
 * (caller should fall back to `extractSignatures`/tree-sitter), or a file with
 * no extractable top-level symbols.
 */
export declare function extractJsSymbols(content: string, filePath: string): string | null

/**
 * Search `content` line-by-line for `pattern` (literal or regex), returning
 * matched lines with context windows and omission markers.
 *
 * Replaces `extractMatchingLines` (contentExtractor.ts) which performed 2–3
 * full `forEach` scans with per-line `toLowerCase` + `RegExp.test`.
 */
export declare function extractMatchingLines(content: string, pattern: string, options?: ExtractMatchingLinesOptions | undefined | null): ExtractMatchingLinesResult

export interface ExtractMatchingLinesOptions {
  /** Treat `pattern` as a regex (default false — literal match). */
  isRegex?: boolean
  /** Case-sensitive match (default false). */
  caseSensitive?: boolean
  /** Lines of context to include around each match (default 0). */
  contextLines?: number
  /** UTF-8 context bytes per side; overrides context_lines when present. */
  contextBytes?: number
  /** Cap the number of matched lines returned. */
  maxMatches?: number
}

export interface ExtractMatchingLinesResult {
  /** Output lines including context and omission markers. */
  lines: Array<string>
  /** 1-based line numbers of actual matches (capped by `max_matches`). */
  matchingLines: Array<number>
  /** Total matches before `max_matches` cap. */
  matchCount: number
  matchRanges: Array<MatchRange>
  /** Zero-based, end-exclusive UTF-8 windows; present only for byte context. */
  byteRanges?: Array<ByteRange>
}

/**
 * Structural skeleton with an `NNN| ` line-number gutter, produced purely by
 * tree-sitter parsing (no regex heuristics). Returns `null` for data/config
 * formats, any language without a wired grammar, content above the 1MB guard,
 * and any skeleton that would not be smaller than the source.
 */
export declare function extractSignatures(content: string, filePath: string): string | null

export interface FileSystemEntry {
  /** Absolute or input-root-relative path as returned by the platform. */
  path: string
  /** Path relative to the query root. */
  relativePath: string
  name: string
  /** "file", "directory", "symlink", or "other". */
  entryType: string
  size?: number
  modifiedMs?: number
  accessedMs?: number
  permissions?: string
  extension?: string
  /** Output depth where direct children are 0. */
  depth: number
}

export interface FileSystemQueryOptions {
  path: string
  /** Include the root path itself in results (default false). */
  includeRoot?: boolean
  /** Descend into child directories (default true). */
  recursive?: boolean
  /** Maximum depth where direct children are depth 1. */
  maxDepth?: number
  /** Minimum depth where direct children are depth 1. */
  minDepth?: number
  /** Include dotfiles and dot-directories (default true). */
  showHidden?: boolean
  /** Match basename globs, OR-combined. */
  names?: Array<string>
  /**
   * Match file extensions, OR-combined. Values may include a leading dot.
   * Directories are preserved so recursive structure views can keep context.
   */
  extensions?: Array<string>
  /** Match full path glob. */
  pathPattern?: string
  /** Rust regex against basename. */
  regex?: string
  /** POSIX find-style entry type: f=file, d=directory, l=symlink. */
  entryType?: string
  /** Match only empty files or directories. */
  empty?: boolean
  /** Modified within a duration string such as 7d, 2h, 30m. */
  modifiedWithin?: string
  /** Modified before a duration string such as 30d. */
  modifiedBefore?: string
  /** Accessed within a duration string such as 7d. */
  accessedWithin?: string
  /** Size greater than a string such as 100k, 1m, 500b. */
  sizeGreater?: string
  /** Size less than a string such as 100k, 1m, 500b. */
  sizeLess?: string
  /** Exact octal permissions, e.g. 644. */
  permissions?: string
  executable?: boolean
  readable?: boolean
  writable?: boolean
  excludeDir?: Array<string>
  /**
   * Stop walking after `limit` returned entries. Default true for interactive
   * tools; set false when exact total_discovered is more important than
   * latency.
   */
  stopAtLimit?: boolean
  /**
   * Store at most this many matching entries while still counting matches
   * when stop_at_limit is false.
   */
  limit?: number
}

export interface FileSystemQueryResult {
  entries: Array<FileSystemEntry>
  totalDiscovered: number
  wasCapped: boolean
  skipped: number
  permissionDenied: number
  warnings: Array<string>
}

/**
 * Filter and optionally trim a unified diff patch.
 *
 * Replaces `filterPatch` + `trimDiffContext` from `utils/parsers/diff.ts` which
 * called `patch.split('
')` independently in both functions. This combines
 * both operations in a single pass.
 */
export declare function filterPatch(patch: string, options?: FilterPatchOptions | undefined | null): string

export interface FilterPatchOptions {
  /** Only keep additions at these new-file line numbers. */
  additions?: Array<number>
  /** Only keep deletions at these original-file line numbers. */
  deletions?: Array<number>
  /** Apply context trimming (equivalent to `trimDiffContext`, default false). */
  trimContext?: boolean
  /** Context window size when `trim_context` is true (default 2). */
  contextLines?: number
}

/**
 * Native in-file references (server-free) for the JS/TS symbol under
 * `(line, character)` (0-based, UTF-16), as a JSON `Range[]` covering the
 * declaration and every resolved in-file reference (declaration first).
 *
 * **Same-file only.** oxc resolves bindings within one module; cross-file
 * references require a language server. No type inference. Returns `null` for
 * non-JS/TS files, oversized content, a parse failure, or when the cursor is
 * not on a resolvable binding/reference.
 */
export declare function findInFileReferences(content: string, filePath: string, line: number, character: number): string | null

/** Convert a `file://` URI string back to an absolute filesystem path. */
export declare function fromUri(uri: string): string

/**
 * Canonical parser-family inventory for runtime selectors and agent context.
 * Names, aliases, extensions, and capability flags all come from the same
 * registry used by structural search, signatures, graph facts, and LSP grammar
 * detection; consumers must not maintain a parallel language table.
 */
export declare function getGrammarCapabilities(): Array<GrammarCapability>

/**
 * JSON array describing graph fact coverage by extension/language. This is an
 * agent-facing capability matrix, not proof that every fact family is complete.
 */
export declare function getGraphFactCapabilities(): string

/**
 * Return the default language server configuration for `file_path` inside
 * `workspace_root`.
 */
export declare function getLanguageServerForFile(filePath: string, workspaceRoot: string): JsLanguageServerConfig | null

/**
 * Returns a sorted list of JS char offsets (UTF-16 code units) where
 * top-level semantic blocks begin in `content`.
 *
 * Uses registered Tree-sitter body queries; see `getSupportedSignatureExtensions`
 * for the compiled language set. Unsupported/plain-text inputs and files
 * above the 1 MB guard return `[]`.
 *
 * Char offsets match JavaScript `string.substring()` — pass them directly to
 * JavaScript string slicing without conversion.
 *
 * Runs on libuv's worker pool (tree-sitter parse is CPU-bound) so a large file
 * never blocks the event loop. Returns a Promise from JavaScript.
 */
export declare function getSemanticBoundaryOffsets(content: string, filePath: string): Promise<unknown>

/**
 * Canonical lowercase extensions (no leading dot) that can produce native
 * `GraphFacts`. JS/TS use the OXC lane; other entries use tree-sitter syntax
 * inventory. LSP proof is still required for semantic reference certainty.
 */
export declare function getSupportedGraphFactExtensions(): Array<string>

/**
 * Canonical list of file extensions (lowercase, no leading dot) handled by the
 * native oxc JS/TS path (`extractJsSymbols` / `findInFileReferences`). Callers
 * should gate native dispatch on this list rather than hardcoding it, so the
 * Rust and JS sides never drift.
 */
export declare function getSupportedJsTsExtensions(): Array<string>

/**
 * Returns all first-class extensions. Every canonical grammar has a
 * function-body query, so structural, signature, and graph capabilities agree.
 */
export declare function getSupportedSignatureExtensions(): Array<string>

export declare function getSupportedStructuralExtensions(): Array<string>

/**
 * One parser entry from the canonical grammar registry. Consumers use this
 * runtime inventory for language selection and agent guidance instead of
 * maintaining extension/name tables outside the engine.
 */
export interface GrammarCapability {
  language: string
  languageId?: string
  selectorAliases: Array<string>
  extensions: Array<string>
  structuralSearch: boolean
  signatureOutline: boolean
  graphFacts: boolean
}

export interface GraphFactsScanDiagnostic {
  relativePath: string
  code: string
  message: string
}

export interface GraphFactsScanEntry {
  relativePath: string
  factsJson: string
  referenceCounts: Array<GraphReferenceCount>
}

export interface GraphFactsScanOptions {
  path: string
  excludeDir?: Array<string>
  maxFiles?: number
  maxFileBytes?: number
}

export interface GraphFactsScanResult {
  schemaVersion: number
  entries: Array<GraphFactsScanEntry>
  skipped: Array<GraphFactsScanDiagnostic>
  candidatePaths: Array<string>
  filesSkipped: number
  truncated: boolean
}

export interface GraphReferenceCount {
  name: string
  count: number
}

export interface IndexBuildRequest {
  store: IndexStoreOptions
  exclusions?: Array<string>
  maxFiles?: number
  maxEntries?: number
  maxDepth?: number
  maxFileBytes?: number
  maxSourceBytes?: number
}

export interface IndexBuildResult {
  generation: number
  rootId: string
  canonicalRoot: string
  snapshot: string
  documentCount: number
  indexedSourceBytes: number
  symbolCount: number
  complete: boolean
  truncated: boolean
  limitReason?: string
  excludedPaths: Array<string>
  skippedBinary: Array<string>
  skippedTooLarge: Array<string>
  skippedSymlinks: Array<string>
  unverifiable: Array<string>
  freshness: IndexFreshnessResult
  usable: boolean
}

export interface IndexFreshnessResult {
  checked: number
  fresh: number
  generationComplete: boolean
  traversalComplete: boolean
  scannedEntries: number
  added: Array<string>
  dirty: Array<string>
  deleted: Array<string>
  unverifiable: Array<string>
  canProveAbsence: boolean
}

export interface IndexQueryMatchResult {
  path: string
  line: number
  column: number
  startByte: number
  endByte: number
  value: string
  symbolKind?: string
}

export interface IndexQueryRequest {
  store: IndexStoreOptions
  text: string
  /** `content` or `symbol`. */
  kind: string
  caseSensitive?: boolean
  offset?: number
  limit?: number
  /** Bind a continuation to the generation returned by the prior page. */
  expectedGeneration?: number
  freshnessMaxEntries?: number
  freshnessMaxDepth?: number
}

export interface IndexQueryResult {
  generation: number
  rootId: string
  canonicalRoot: string
  snapshot: string
  matches: Array<IndexQueryMatchResult>
  totalMatches: number
  nextOffset?: number
  exclusions: Array<string>
  freshness: IndexFreshnessResult
  usable: boolean
  absenceProven: boolean
  diagnostic?: string
}

export declare function indexStatus(options: IndexStatusRequest): Promise<unknown>

export interface IndexStatusRequest {
  store: IndexStoreOptions
  freshnessMaxEntries?: number
  freshnessMaxDepth?: number
}

export interface IndexStatusResult {
  indexed: boolean
  usable: boolean
  rootId: string
  canonicalRoot: string
  generation?: number
  snapshot?: string
  documentCount: number
  indexedSourceBytes: number
  exclusions: Array<string>
  freshness?: IndexFreshnessResult
  diagnostic?: string
}

export interface IndexStoreOptions {
  home: string
  rootId: string
  rootPath: string
  sourceCommit?: string
  sourceTree?: string
  indexSchemaVersion: number
  parserSchemaVersion: number
  toolVersion: string
  maxGenerations?: number
  maxBytes?: number
}

/**
 * Return a bounded, paginated syntax-tree view using the structural grammar
 * registry. Parsing and traversal run on libuv's worker pool.
 */
export declare function inspectSyntaxTree(content: string, filePath: string, options?: SyntaxTreeInspectOptions | undefined | null): Promise<unknown>

/** Check whether `command` is available on `PATH`. */
export declare function isCommandAvailable(command: string): boolean

export interface JsCodeSnippet {
  uri: string
  range: JsRange
  content: string
  symbolKind?: string
  displayRange?: any
}

export interface JsExactPosition {
  line: number
  character: number
}

export interface JsFuzzyPosition {
  symbolName: string
  lineHint?: number
  orderHint?: number
}

export interface JsLanguageServerConfig {
  command: string
  args?: Array<string>
  workspaceRoot: string
  languageId?: string
  initializationOptions?: any
  /** Extra environment variables to inject into the language server process. */
  env?: Record<string, string>
  /**
   * OS-level memory cap for the spawned server process, in MiB. `None`
   * applies a generous 4 GiB default; `Some(0)` disables the cap for
   * servers that legitimately need more (huge monorepo indexes). Internal
   * buffer bounds do not protect the host from a runaway child — this does.
   */
  maxMemoryMb?: number
}

/**
 * Serialize a JSON value to YAML — the formatter for every MCP tool
 * response. Optional key sorting and priority-key ordering; multiline
 * strings become block scalars. Emission is locked by yaml_utils tests.
 */
export declare function jsonToYamlString(jsonObject: any, config?: YamlConversionConfig | undefined | null): string

export interface JsRange {
  start: JsExactPosition
  end: JsExactPosition
}

export interface JsResolvedSymbol {
  position: JsExactPosition
  foundAtLine: number
  lineOffset: number
  lineContent: string
}

/**
 * Mask secrets in place: every even-indexed char of a matched secret becomes
 * `*`, preserving partial readability. File-context patterns are skipped.
 */
export declare function maskSensitiveData(text: string): string

export interface MatchRange {
  /** 1-based inclusive start line. */
  start: number
  /** 1-based inclusive end line. */
  end: number
}

/**
 * Precise position of one captured metavariable node. Line is 1-based (usable
 * as an `lspSearch` `lineHint`); columns are 0-based UTF-16 code-unit
 * offsets — the same convention as `StructuralMatch.start_col` and LSP.
 */
export interface MetavarRange {
  text: string
  line: number
  column: number
  endLine: number
  endColumn: number
}

/**
 * Full minification on libuv's worker pool.
 * Returns a Promise from JavaScript and does not block the event loop.
 */
export declare function minifyContent(content: string, filePath: string): Promise<unknown>

export interface MinifyResult {
  content: string
  failed: boolean
  /** Strategy name or "failed" */
  type: string
  reason?: string
}

/**
 * Parse ripgrep `--json` NDJSON stdout into structured files + stats.
 *
 * Replaces the TypeScript `parseRipgrepJson` (utils/parsers/ripgrep.ts) which
 * used `JSON.parse` + Zod `safeParse` per NDJSON line and a `[...value]`
 * UTF-16 spread per match snippet. A single `serde_json` streaming pass with
 * no per-line schema validation.
 */
export declare function parseRipgrepJson(stdout: string, options?: RipgrepParseOptions | undefined | null): RipgrepParseResult

export declare const enum PatchLineType {
  Addition = 'Addition',
  Deletion = 'Deletion',
  Context = 'Context',
}

export declare function pooledLspClientConfigs(): Promise<Array<JsLanguageServerConfig>>

export declare function pooledLspClientCount(): number

/**
 * Cross-platform filesystem traversal and metadata filtering for local tools.
 *
 * Replaces the POSIX `find`/`ls` execution paths in octocode-native while
 * keeping MCP response shaping in TypeScript.
 */
export declare function queryFileSystem(options: FileSystemQueryOptions): Promise<unknown>

export declare function queryIndex(options: IndexQueryRequest): Promise<unknown>

export declare function releasePooledLspClient(config: JsLanguageServerConfig): Promise<boolean>

/**
 * Resolve a fuzzy symbol position (name + optional line hint) to an exact
 * line/character position inside the file at `file_path`.
 */
export declare function resolvePosition(filePath: string, fuzzy: JsFuzzyPosition): JsResolvedSymbol

/**
 * Resolve a fuzzy symbol position against in-memory `content` rather than
 * reading from disk. Use when the caller already holds the file text.
 */
export declare function resolvePositionFromContent(content: string, fuzzy: JsFuzzyPosition): JsResolvedSymbol

/** Walk upward from `file_path` to find the workspace root. */
export declare function resolveWorkspaceRootForFile(filePath: string): string

export interface RipgrepFile {
  path: string
  matchCount: number
  matches: Array<RipgrepMatch>
}

export interface RipgrepMatch {
  /** 1-based line number. */
  line: number
  /** 0-based column offset of the first submatch. */
  column: number
  /** Assembled match + context window, truncated to `max_snippet_chars`. */
  value: string
  /** Frequency for this value when `count_unique` is enabled. */
  count?: number
  /**
   * AST node-kind label (declaration|import|export|callsite|identifier|
   * comment|string|configKey|heading) when `classify_matches` is enabled.
   * `None` when classification was off, the language is unsupported, or the
   * file failed to parse.
   */
  kind?: string
  /** Deterministic relevance hint (0.0..1.0) derived from `kind`. */
  scoreHint?: number
}

export interface RipgrepParseOptions {
  /** Number of context lines around each match (default 0). */
  contextLines?: number
  /** Max Unicode chars per match snippet (default 500). */
  maxSnippetChars?: number
}

export interface RipgrepParseResult {
  files: Array<RipgrepFile>
  stats: RipgrepStats
}

export interface RipgrepPatternValidationResult {
  valid: boolean
  error?: string
}

/**
 * Options for the in-process ripgrep search (`searchRipgrep`). Field semantics
 * mirror the ripgrep CLI flags the old `RipgrepCommandBuilder` emitted, so the
 * search behaves identically to shelling out to `rg`.
 */
export interface RipgrepSearchOptions {
  /** Search root: a directory (recursive) or a single file. */
  path: string
  /** The search pattern (rg's positional pattern / `keywords`). */
  pattern: string
  /** Treat the pattern as a literal string, not a regex (`-F`). */
  fixedString?: boolean
  /** Use the PCRE2 engine for lookaround/backreferences (`-P`). */
  perlRegex?: boolean
  /** Case-sensitive match (`-s`). Wins over `case_insensitive`. */
  caseSensitive?: boolean
  /** Case-insensitive match (`-i`). Default is smart-case (`-S`). */
  caseInsensitive?: boolean
  /** Match whole words only (`-w`). */
  wholeWord?: boolean
  /** Invert: report non-matching lines (`-v`). */
  invertMatch?: boolean
  /** Multi-line mode: `.` and the pattern may span lines (`-U`). */
  multiline?: boolean
  /** In multi-line mode, let `.` match newlines (`--multiline-dotall`). */
  multilineDotall?: boolean
  /** List only the paths of files that contain a match (`-l`). */
  filesOnly?: boolean
  /** List only the paths of files with no match (`--files-without-match`). */
  filesWithoutMatch?: boolean
  /** Per-file count of matching lines (`-c`). */
  countLinesPerFile?: boolean
  /** Per-file count of individual matches (`--count-matches`). */
  countMatchesPerFile?: boolean
  /** Context lines around each match (`-C`). */
  contextLines?: number
  /** Restrict to a ripgrep file type, e.g. `ts`, `py` (`-t`). */
  langType?: string
  /** Include globs (`-g <glob>`). */
  include?: Array<string>
  /** Exclude globs (`-g !<glob>`). */
  exclude?: Array<string>
  /** Exclude directories (`-g !<dir>/`). */
  excludeDir?: Array<string>
  /** Do not honor .gitignore/.ignore/etc. (`--no-ignore`). */
  noIgnore?: boolean
  /** Search hidden files and directories (`--hidden`). */
  hidden?: boolean
  /**
   * Maximum directory descent below the search root. `0` searches files
   * directly in the root, `1` includes one nested directory level, and so on.
   */
  maxDepth?: number
  /** Sort key: `path` (default), `modified`, `accessed`, or `created`. */
  sort?: string
  /** Reverse the sort order (`--sortr`). */
  sortReverse?: boolean
  /** Max Unicode chars per assembled snippet (default 500). */
  maxSnippetChars?: number
  /**
   * When true, label each match with its AST node kind (tree-sitter) for
   * language-aware ranking. Optional and capped by the caller; degrades to
   * unlabeled matches on unsupported/unparseable files.
   */
  classifyMatches?: boolean
  /**
   * Emit one match per *submatch* with `value` set to the matched span
   * (not the whole line) — ripgrep's `-o`/`--only-matching`. The win on a
   * minified one-liner: line mode can only count hits, this enumerates them.
   */
  onlyMatching?: boolean
  /**
   * With `only_matching`, widen each span by this many characters on each
   * side (char-boundary safe), marking trimmed sides with `…`. 0/unset =
   * the bare matched span.
   */
  matchWindow?: number
  /**
   * With `only_matching`, collapse duplicate values per file, preserving
   * first-occurrence order and anchor.
   */
  unique?: boolean
  /**
   * With `only_matching`, collapse duplicate values and attach their
   * frequency, sorted by count descending.
   */
  countUnique?: boolean
  /**
   * Native collection guard: stop after this many matched files have been
   * collected. Distinct from native runtime maxFiles, which is a per-page UI
   * size, not an engine resource cap.
   */
  maxCollectedFiles?: number
}

export interface RipgrepStats {
  matchCount?: number
  matchedLines?: number
  filesMatched?: number
  filesSearched?: number
  bytesSearched?: number
  searchTime?: string
  capped?: boolean
  capReason?: string
  /** Traversal or per-file search failures; nonzero means incomplete coverage. */
  errorCount?: number
  /** Bounded first failure detail. Counts include every observed failure. */
  firstError?: string
}

/**
 * Read `file_path` from disk after canonicalizing it and confirming it is an
 * absolute regular file.
 */
export declare function safeReadFile(filePath: string): string

/**
 * Read only a bounded line window around `line_zero_based` after canonicalizing
 * the path or file:// URI and confirming it is an absolute regular file.
 */
export declare function safeReadLineWindow(filePath: string, lineZeroBased: number, contextLines: number): string

export interface SanitizationResult {
  content: string
  hasSecrets: boolean
  secretsDetected: Array<string>
  warnings: Array<string>
}

/**
 * Detect and redact all secrets from `content`, returning the sanitized string
 * with `[REDACTED-*]` placeholders plus detection metadata. `file_path` gates
 * file-context patterns (e.g. Kubernetes/`.env` secrets).
 *
 * The scan is wrapped in `catch_unwind` — same guard as binary/signatures/
 * structural — so a panic on pathological input becomes a catchable JS error
 * instead of aborting the Node process, and never silently falls through to
 * returning unredacted content.
 */
export declare function sanitizeContent(content: string, filePath?: string | undefined | null): SanitizationResult

/**
 * Scan graph-fact-capable files, read them, and extract per-file facts in one
 * worker-pool operation. Cross-file policy and agent-facing output stay in
 * native runtime.
 */
export declare function scanGraphFacts(options: GraphFactsScanOptions): Promise<unknown>

/**
 * Run ripgrep in-process: walk `path`, search every file with ripgrep's own
 * engine, and return the same `{ files, stats }` shape the `--json` parser
 * produced. Replaces shelling out to an `rg` binary (and the `@vscode/ripgrep`
 * bundle) — octocode is now its own source of ripgrep.
 *
 * Runs on the libuv thread pool so the filesystem walk never blocks the event
 * loop, mirroring the old async `spawn` of `rg`.
 */
export declare function searchRipgrep(options: RipgrepSearchOptions): Promise<unknown>

/** Native exports. */
export declare const SIGNATURES_ONLY_HINT: string

/**
 * Paginate `content` by char offset + length, with optional line-boundary
 * snapping. Replaces both the char-mode conversion block in `applyPagination`
 * and the `sliceByCharRespectLines` helper.
 */
export declare function sliceContent(content: string, charOffset: number, charLength: number, options?: SliceContentOptions | undefined | null): SliceContentResult

export interface SliceContentOptions {
  /** When true, snap start to line start and end to line end (default false). */
  snapToLineBoundary?: boolean
}

export interface SliceContentResult {
  text: string
  /** Actual start char offset (may differ from requested when snapping). */
  charOffset: number
  charLength: number
  byteOffset: number
  byteLength: number
  hasMore: boolean
  nextCharOffset?: number
}

/**
 * A structural match with stable evidence metadata. Existing
 * `StructuralMatch` remains unchanged for the legacy APIs; detailed APIs add
 * IDs and confidence without forcing old callers to carry metadata.
 */
export interface StructuralDetailedMatch {
  id: string
  startLine: number
  endLine: number
  startCol: number
  endCol: number
  text: string
  metavars: Record<string, Array<string>>
  metavarRanges: Record<string, Array<MetavarRange>>
  nodeKind?: string
  confidence: string
}

export interface StructuralDiagnostic {
  code: string
  severity: string
  stage: string
  message: string
  path?: string
  recovery?: string
}

/**
 * One structural match. Line numbers are 1-based so `start_line` can be fed
 * directly as an `lspSearch` `lineHint`; columns are 0-based UTF-16
 * code-unit offsets (converted from tree-sitter's native byte columns to match
 * the resolver, signatures, and LSP layers).
 */
export interface StructuralMatch {
  startLine: number
  endLine: number
  startCol: number
  endCol: number
  text: string
  /**
   * Captured metavariables. `$X` yields a single-element list;
   * `$$$ARGS` yields the full list of captured nodes. Keyed by the bare
   * metavar name (no leading `$`).
   */
  metavars: Record<string, Array<string>>
  /**
   * Per-capture precise ranges, parallel to `metavars` (same keys, same
   * order). Lets an agent hand a capture straight to LSP without re-search.
   */
  metavarRanges: Record<string, Array<MetavarRange>>
}

export interface StructuralQueryExplanation {
  kind: string
  source: string
  literalAnchor?: string
  preFilter: string
  unsafeReason?: string
  diagnostics: Array<StructuralDiagnostic>
}

/**
 * In-process structural rewrite for a single file content. `rule_config_json`
 * is a complete ast-grep inline-rule JSON string (language, rule, fix, etc.).
 * Returns a JSON string of `StructuralRewriteMatch[]`.
 */
export declare function structuralRewriteContent(content: string, ruleConfigJson: string): string

/**
 * In-process structural rewrite over a file tree. Walks files in parallel,
 * applies the inline rule to each, and returns a JSON string of
 * `Array<{ path: string; matches: StructuralRewriteMatch[] }>`.
 * Runs on the libuv worker pool — returns a Promise.
 */
export declare function structuralRewriteFiles(options: StructuralRewriteFilesOptions): Promise<unknown>

/**
 * Options for in-process structural rewrite over a file tree. The rule config
 * must be a complete ast-grep inline-rule JSON object (language, rule, fix, etc.).
 */
export interface StructuralRewriteFilesOptions {
  path: string
  /** Full ast-grep inline-rule config as a JSON string. */
  ruleConfigJson: string
  include?: Array<string>
  exclude?: Array<string>
  excludeDir?: Array<string>
  hidden?: boolean
  noIgnore?: boolean
  maxDepth?: number
  maxFiles?: number
  maxFileBytes?: number
}

/**
 * Structural (AST) search — octocode's L2 layer. Resolves the grammar from
 * `file_path`'s extension and matches a code-shaped `pattern` OR a YAML `rule`
 * (exactly one). Returns node ranges (1-based lines, ready as `lineHint`s)
 * plus captured metavariables. Throws on unsupported extension, invalid
 * pattern/rule, or both/neither query supplied.
 *
 * Runs on libuv's worker pool (parsing is tree-sitter, CPU-bound) so a large
 * file never blocks the event loop. Returns a Promise from JavaScript.
 */
export declare function structuralSearch(content: string, filePath: string, pattern?: string | undefined | null, rule?: string | undefined | null): Promise<unknown>

/**
 * Detailed structural search. Unlike `structuralSearch`, unsupported
 * extensions and invalid queries are represented as status + diagnostics so
 * callers can distinguish true empty results from weak evidence.
 */
export declare function structuralSearchDetailed(content: string, filePath: string, pattern?: string | undefined | null, rule?: string | undefined | null): StructuralSearchDetailedResult

export interface StructuralSearchDetailedFileResult {
  path: string
  status: string
  languageId?: string
  skippedReason?: string
  matches: Array<StructuralDetailedMatch>
  diagnostics: Array<StructuralDiagnostic>
}

export interface StructuralSearchDetailedResult {
  path: string
  analyzer: string
  analyzerVersion: string
  status: string
  languageId?: string
  query: StructuralQueryExplanation
  matches: Array<StructuralDetailedMatch>
  diagnostics: Array<StructuralDiagnostic>
}

export interface StructuralSearchFileResult {
  path: string
  matches: Array<StructuralMatch>
}

/**
 * Runs on libuv's worker pool — the directory walk + per-file parse is
 * CPU/IO-bound and can span thousands of files. Returns a Promise from
 * JavaScript.
 */
export declare function structuralSearchFiles(options: StructuralSearchFilesOptions): Promise<unknown>

export declare function structuralSearchFilesDetailed(options: StructuralSearchFilesOptions): StructuralSearchFilesDetailedResult

export interface StructuralSearchFilesDetailedResult {
  scanTruncated: boolean
  files: Array<StructuralSearchDetailedFileResult>
  totalMatches: number
  parsedFiles: number
  skippedByPreFilter: number
  skippedUnsupported: number
  skippedUnreadable: number
  skippedLarge: number
  analyzer: string
  analyzerVersion: string
  status: string
  query: StructuralQueryExplanation
  diagnostics: Array<StructuralDiagnostic>
  warnings: Array<string>
}

export interface StructuralSearchFilesOptions {
  path: string
  pattern?: string
  rule?: string
  include?: Array<string>
  /**
   * File-path globs to skip (gitignore-style, e.g. `"*.min.js"`, `"src/gen/**"`).
   * Mirrors local-search `exclude` so it is honored on the structural
   * lane too — previously silently dropped (typed-contract violation).
   */
  exclude?: Array<string>
  excludeDir?: Array<string>
  /**
   * Include hidden (dot) files. `None` preserves the default walker behavior
   * (hidden ignored); `Some(true)` forces them in.
   */
  hidden?: boolean
  /**
   * Bypass `.gitignore`/`.ignore` rules. `None` preserves defaults; `Some(true)`
   * searches files normally hidden by ignore files (mirrors local-search `noIgnore`).
   */
  noIgnore?: boolean
  /** Maximum path depth below a directory root (1 = direct files; 0 = no descent). `None` = unbounded. */
  maxDepth?: number
  maxFiles?: number
  maxFileBytes?: number
}

export interface StructuralSearchFilesResult {
  scanTruncated: boolean
  status: string
  /**
   * Query planning evidence computed before the scan. Keeping it on the
   * asynchronous result lets callers explain zero matches without repeating
   * the full directory walk on the JavaScript event loop.
   */
  query?: StructuralQueryExplanation
  diagnostics: Array<StructuralDiagnostic>
  files: Array<StructuralSearchFileResult>
  totalMatches: number
  parsedFiles: number
  skippedByPreFilter: number
  /**
   * Candidate files whose extension has no grammar — not evaluated, hence
   * not proof of absence. Mirrors the detailed result's counter so the two
   * shapes agree and the warning text can't collapse unevaluated into
   * anchor-absent.
   */
  skippedUnsupported: number
  skippedUnreadable: number
  skippedLarge: number
  warnings: Array<string>
}

export interface SyntaxTreeInspectOptions {
  namedOnly?: boolean
  nodeOffset?: number
  nodeLimit?: number
}

export interface SyntaxTreeInspectResult {
  nodes: Array<SyntaxTreeNode>
  totalNodes: number
  nextOffset?: number
  status: string
  diagnostics: Array<StructuralDiagnostic>
}

export interface SyntaxTreeNode {
  id: number
  parentId?: number
  kind: string
  named: boolean
  startLine: number
  startColumn: number
  endLine: number
  endColumn: number
  startByte: number
  endByte: number
}

/**
 * Convert a human-readable symbol kind string back to the LSP `SymbolKind`
 * numeric code. Unknown strings return `13` (Variable).
 */
export declare function toLspSymbolKind(kind: string): number

/** Convert a filesystem path to a `file://` URI string. */
export declare function toUri(path: string): string

/** Validate that `command` resolves to an executable LSP server binary. */
export declare function validateLspServerPath(command: string): string

export declare function validateRipgrepPattern(pattern: string, fixedString?: boolean | undefined | null, perlRegex?: boolean | undefined | null): RipgrepPatternValidationResult

export interface YamlConversionConfig {
  sortKeys?: boolean
  keysPriority?: Array<string>
}
