#!/usr/bin/env node
// KPI: bytes per answer and lead share against the rg/gh shell recipes.
// Exits 1 when a regression gate fails (see the gates at the end).
//
// Minimal port of the recovered kpi script (git blob d2bd50a1):
// only the competitors section survives; its complexity, ratings and
// carried-value sections read folders that no longer exist.
//
//   node octocode-local-testing/harness/kpi.mjs --label=<name> [--competitors=<results.json>] [--out=<dir>]
//
// Without --competitors it runs harness/competitors.mjs (OCTOCODE_BETA=true,
// saved as results/competitors-kpi-<label>.json). The environment passes
// through, so OCTOCODE_NATIVE_BINDING (with NODE_ENV=development) measures a
// candidate addon and OCTOCODE_COMPETITOR_GITHUB=0 skips network tasks.
// Writes <out>/KPI-<label>.json and .md (default .octocode/evals/<date>-kpi).
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { ROOT } from './mcp-client.mjs';

const RESULTS = path.join(ROOT, 'octocode-local-testing/results');
const argv = process.argv.slice(2);
const opt = name => argv.find(a => a.startsWith(`--${name}=`))?.slice(name.length + 3);
const LABEL = opt('label') ?? 'run';
const OUT = path.resolve(opt('out') ?? path.join(ROOT, '.octocode/evals', `${new Date().toISOString().slice(0, 10)}-kpi`));
const median = xs => {
  const s = xs.filter(x => x != null && Number.isFinite(x)).sort((a, b) => a - b);
  if (!s.length) return null;
  const m = Math.floor(s.length / 2);
  return +(s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2).toFixed(3);
};
const fmt = v => (v == null ? '—' : typeof v === 'number' ? (Number.isInteger(v) ? v.toLocaleString('en-US') : String(+v.toFixed(3))) : String(v));
const TOOL_ORDER = ['localSearch', 'localFetch', 'structureSearch', 'astSearch', 'lspSearch', 'ghSearchRepo', 'ghSearchCode', 'ghStructure', 'ghGetFileContent', 'ghSearchHistory', 'ghGetHistoryItem', 'artifactSearch', 'clasify', 'ghCloneRepo', 'astTopology', 'astRewrite'];

function competitorsFile() {
  if (opt('competitors')) return path.resolve(opt('competitors'));
  const saveAs = `competitors-kpi-${LABEL}`;
  console.error(`[kpi] running competitors.mjs (OCTOCODE_BETA=true) → results/${saveAs}.json`);
  const r = spawnSync(process.execPath, [path.join(ROOT, 'octocode-local-testing/harness/competitors.mjs'), `--save-as=${saveAs}`], {
    cwd: ROOT, env: { ...process.env, OCTOCODE_BETA: 'true' }, encoding: 'utf8', maxBuffer: 1 << 28,
  });
  const file = path.join(RESULTS, `${saveAs}.json`);
  if (!fs.existsSync(file)) throw new Error(`competitors run wrote nothing: ${r.stderr.slice(-400)}`);
  return file;
}

function competitorsKpi(file) {
  const j = JSON.parse(fs.readFileSync(file, 'utf8'));
  const ran = j.tasks.filter(t => t.status === 'ran');
  const o = j.overall;
  const small = ran.filter(t => t.competitor.bytes <= 1000);
  const whole = {
    correct: `${o.octocodeCorrect}/${o.ran}`, correctShell: `${o.competitorCorrect}/${o.ran}`,
    medianBytesRatio: o.medianBytesRatio, medianBytesRatioUnfiltered: o.medianBytesRatioUnfiltered,
    medianMsRatio: o.medianMsRatio, medianCallsRatio: o.medianCallsRatio,
    hintsShareSmall: median(small.map(t => t.octocode.sensors?.hintsShare)), smallTasks: small.length,
    hintsShareAll: o.medianHintsShare, leadShareAll: o.medianLeadShare,
    leadShareSmall: median(small.map(t => t.octocode.sensors?.leadShare)),
    neverTrimViolations: Array.isArray(o.neverTrimViolations) ? o.neverTrimViolations.length : o.neverTrimViolations,
    schemaErrors: o.schemaErrors?.total ?? null,
  };
  const perTool = {};
  for (const t of ran) {
    const x = (perTool[t.tool] ??= { tasks: 0, correct: 0, ocBytes: 0, shBytes: 0, leads: [], hints: [] });
    x.tasks++; x.correct += t.octocode.ok ? 1 : 0;
    x.ocBytes += t.octocode.bytes; x.shBytes += t.competitor.bytes;
    x.leads.push(t.octocode.sensors?.leadShare); x.hints.push(t.octocode.sensors?.hintsShare);
  }
  for (const x of Object.values(perTool)) {
    x.bytesRatio = x.shBytes ? +(x.ocBytes / x.shBytes).toFixed(2) : null;
    x.leadShareMedian = median(x.leads); x.hintsShareMedian = median(x.hints);
    delete x.leads; delete x.hints;
  }
  const skipped = j.tasks.filter(t => t.status !== 'ran').map(t => `${t.id} ${t.tool}: ${t.skipReason ?? t.error}`);
  return { file: path.relative(ROOT, file), at: j.at, whole, perTool, skipped };
}

const comp = competitorsKpi(competitorsFile());
const w = comp.whole;
fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, `KPI-${LABEL}.json`), JSON.stringify({ label: LABEL, at: new Date().toISOString(), competitors: comp }, null, 2));
const L = [
  `# KPI: ${LABEL}`, '',
  `Generated by \`octocode-local-testing/harness/kpi.mjs --label=${LABEL}\` from \`${comp.file}\` (${comp.at}).`,
  `Skipped: ${comp.skipped.join('; ') || 'none'}.`, '',
  '| KPI | Value |', '|---|--:|',
  `| Correct answers (rg/gh) | ${w.correct} (${w.correctShell}) |`,
  `| Median bytes ratio vs rg/gh (B7) | ${fmt(w.medianBytesRatio)} |`,
  `| Median bytes ratio vs unfiltered shell | ${fmt(w.medianBytesRatioUnfiltered)} |`,
  `| Median calls ratio · ms ratio | ${fmt(w.medianCallsRatio)} · ${fmt(w.medianMsRatio)} |`,
  `| Hints share, small tasks (B9; ${w.smallTasks} tasks with rg/gh ≤ 1,000 B) | ${fmt(w.hintsShareSmall)} |`,
  `| Hints share, all tasks · lead share, all · lead share, small | ${fmt(w.hintsShareAll)} · ${fmt(w.leadShareAll)} · ${fmt(w.leadShareSmall)} |`,
  `| Never-trim violations · schema errors | ${fmt(w.neverTrimViolations)} · ${fmt(w.schemaErrors)} |`,
  '', '| Tool | Tasks | Correct | Bytes (octocode / rg-gh) | Ratio | Lead share | Hints share |', '|---|--:|--:|--:|--:|--:|--:|',
];
for (const t of TOOL_ORDER.filter(t => comp.perTool[t])) {
  const p = comp.perTool[t];
  L.push(`| ${t} | ${p.tasks} | ${p.correct} | ${fmt(p.ocBytes)} / ${fmt(p.shBytes)} | ${fmt(p.bytesRatio)} | ${fmt(p.leadShareMedian)} | ${fmt(p.hintsShareMedian)} |`);
}
fs.writeFileSync(path.join(OUT, `KPI-${LABEL}.md`), `${L.join('\n')}\n`);
process.stdout.write(`${L.join('\n')}\n`);

// Regression gates (decided 2026-10-07): B7 re-baselined at 2.3× with a 2.4× guard;
// B9 keeps read+callers on multi-hit answers, target ≤0.20. Every answer stays correct.
const gates = [
  ['correct answers', w.correct.split('/')[0] === w.correct.split('/')[1], w.correct],
  ['B7 median bytes ratio ≤ 2.4', w.medianBytesRatio != null && w.medianBytesRatio <= 2.4, w.medianBytesRatio],
  ['B9 small-task hints share ≤ 0.20', w.hintsShareSmall != null && w.hintsShareSmall <= 0.2, w.hintsShareSmall],
  ['never-trim violations = 0', !w.neverTrimViolations, w.neverTrimViolations],
];
for (const [name, ok, value] of gates) process.stdout.write(`${ok ? 'PASS' : 'FAIL'} [kpi] ${name} — ${fmt(value)}\n`);
if (gates.some(([, ok]) => !ok)) process.exitCode = 1;
