import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {startServer,rowData,collect,nextHints,checks,writeResults,REPOS,inventoryRows,sourceView,rawPatch} from './mcp-client.mjs';
const {check,summary}=checks('review');const c=await startServer();const calls=[];
const root=path.join(REPOS,'rust');const git=(...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trimEnd();
const sha=git('rev-parse','HEAD'),parent=git('rev-parse','HEAD^');const number=Number(git('log','-1','--format=%s').match(/#(\d+)\)/)?.[1]);
const repo={owner:'tokio-rs',repo:'tokio'};const pr={...repo,operation:'pullRequest',number};
const stats=git('diff','--numstat',parent,sha).split('\n').map(l=>{const[a,d,file]=l.split('\t');return{file,additions:+a,deletions:+d}});
const delta=s=>rawPatch(s).split('\n').filter(l=>/^[+-](?![+-])/.test(l));
const invoke=async(label,tool,q,lead)=>{const e=lead?await c.follow(lead):await c.call(tool,q);calls.push({label,tool,ms:e.ms,bytes:Buffer.byteLength(e.text),error:e.isError||e.rowErrors>0,args:q,data:e.sc});check(label+' succeeds',!e.isError&&!e.rowErrors,e.text.slice(0,90));return e};
try{
const meta=await invoke('PR metadata','ghGetHistoryItem',pr);const m=rowData(meta)?.pullRequests?.[0];check('PR pins source and merge SHA',/^[a-f0-9]{40}$/.test(m?.sourceSha)&&m?.mergeCommitSha===sha);
const files=await invoke('PR changed-file metadata','ghGetHistoryItem',{...pr,sections:['files']});const changed=inventoryRows(rowData(files)?.pullRequests?.[0]?.files);check('PR file list and counts match git',changed.length===stats.length&&stats.every(g=>changed.some(f=>f.path===g.file&&f.additions===g.additions&&f.deletions===g.deletions)));
const selected=await invoke('PR selected patch','ghGetHistoryItem',{...pr,sections:['patches'],include:[stats[0].file]});const all=await invoke('PR all patches','ghGetHistoryItem',{...pr,sections:['patches']});
const patchRows=e=>collect(rowData(e),v=>typeof v.patch==='string'&&typeof v.path==='string');
check('selected patch excludes unrelated files',patchRows(selected).length===1&&patchRows(selected)[0].path===stats[0].file);
for(const e of [selected,all])check((e===selected?'selected':'all')+' PR patch deltas equal git',patchRows(e).length>0&&patchRows(e).every(f=>JSON.stringify(delta(f.patch))===JSON.stringify(delta(git('diff',parent,sha,'--',f.path)))));
let page=await invoke('PR patches page 1','ghGetHistoryItem',{...pr,pageSize:1,sections:['patches']});const paths=[];let n=0;for(;page&&n<10;n++){paths.push(...patchRows(page).map(f=>f.path));const next=nextHints(page.sc).find(h=>/\.next\.(?:continuePatch|nextFilePage|nextPage)$/.test(h.path));page=next?await invoke('PR patch continuation '+(n+2),next.tool,next.query,next):null;}
check('PR patch pagination visits both files once',paths.length===stats.length&&new Set(paths).size===stats.length,JSON.stringify(paths));
const commit=await invoke('commit diff','ghGetHistoryItem',{...repo,operation:'commit',ref:sha,sections:['patches'],debug:true});const cd=rowData(commit);check('commit pins SHA and parent',cd?.sha===sha&&cd?.parents?.[0]===parent);check('commit file deltas equal git',cd?.files?.length===stats.length&&cd.files.every(f=>JSON.stringify(delta(f.patch))===JSON.stringify(delta(git('diff',parent,sha,'--',f.path)))));
const comp=await invoke('parent→commit comparison','ghGetHistoryItem',{...repo,operation:'compare',base:parent,head:sha,sections:['patches']});const cf=collect(rowData(comp),f=>typeof f.path==='string'&&typeof f.patch==='string');check('comparison deltas equal commit',cf.length===stats.length&&cf.every(f=>JSON.stringify(delta(f.patch))===JSON.stringify(delta(git('diff',parent,sha,'--',f.path)))));
const route=cd?.hints?.readPullRequest??cd?.hints?.findPullRequest;check('commit offers executable PR discovery',!!route);if(route){const found=await invoke('commit→PR lookup',route.tool,route.query,route);check('commit lookup finds pinned PR',collect(rowData(found),v=>v.number===number).length>0)}
const history=await invoke('path history','ghSearchHistory',{...repo,operation:'commit',path:stats[0].file,pageSize:2});const commits=collect(rowData(history),v=>typeof v.sha==='string').slice(0,2);check('path history nonempty',commits.length>0);for(const h of commits){const read=await invoke('verify history '+h.sha.slice(0,8),'ghGetHistoryItem',{...repo,operation:'commit',ref:h.sha});check('history commit touches requested path',rowData(read)?.files?.some(f=>f.path===stats[0].file));}
const detail=await invoke('PR reviews/comments/commits','ghGetHistoryItem',{...pr,sections:['reviews','comments','reviewComments','commits']});
check('detail request reports review/commit surfaces',JSON.stringify(rowData(detail)).includes('reviews')&&JSON.stringify(rowData(detail)).includes('commits'));
const source=await invoke('exact merged source','ghGetFileContent',{...repo,path:stats[0].file,ref:sha,ranges:['25-100'],minify:'none'});const read=collect(rowData(source),v=>typeof v.content==='string')[0];const content=read&&sourceView(read).text;const original=git('show',sha+':'+stats[0].file).split('\n').slice(24,100).join('\n');check('merged source lines equal git',content?.trimEnd()===original.trimEnd());
const open=await invoke('open PR discovery','ghSearchHistory',{owner:'microsoft',repo:'TypeScript',operation:'pullRequest',state:'open',pageSize:3,concise:false});const candidates=collect(rowData(open),v=>typeof v.number==='number'&&typeof v.title==='string');check('open PR discovery returns candidates',candidates.length>0);if(candidates.length){const live=await invoke('open PR review metadata','ghGetHistoryItem',{owner:'microsoft',repo:'TypeScript',operation:'pullRequest',number:candidates[0].number,sections:['files']});check('open PR exposes source SHA',/^[a-f0-9]{40}$/.test(rowData(live)?.pullRequests?.[0]?.sourceSha));}
}finally{const result=summary();writeResults('review',{at:new Date().toISOString(),sha,parent,number,...result,calls});console.table(calls.map(({label,ms,bytes,error})=>({label,ms,bytes,error})));c.close();process.exitCode=result.failed.length?1:0}
