// @generated by scripts/generate-config-contract.ts from config-contract.json.
// Do not edit; run `yarn workspace @octocodeai/config generate:config-contract`.

export type OutputFormat = "yaml" | "json";
export type StorageMode = "persistent" | "memory";

export interface GitHubConfigOptions {
  /** GitHub REST API root. GitHub Enterprise commonly uses /api/v3. */
  apiUrl?: string;

  /** Use GitHub GraphQL where supported; false forces REST-only access. */
  graphqlEnabled?: boolean;
}

export interface LocalConfigOptions {
  /** Enable local filesystem tools on every runtime surface. */
  /** ENABLE_LOCAL is canonical; OCTOCODE_ENABLE_LOCAL is an alias. */
  enabled?: boolean;

  /** Enable ghCloneRepo and directory materialization. */
  /** Opt-in and requires persistent storage. ENABLE_CLONE is canonical. */
  enableClone?: boolean;

  /** Enable the astRewrite tool. Preview and apply are unavailable while false. */
  enableAstRewrite?: boolean;

  /** Permit hash-guarded astRewrite apply when astRewrite is enabled; preview remains available. */
  enableAstRewriteApply?: boolean;

  /** Extra absolute or home-relative roots added to the allowed home directory. */
  /** The environment value is a comma-separated list. */
  allowedPaths?: string[];

  /** Optional absolute or home-relative workspace root. */
  workspaceRoot?: string;
}

export interface ToolsConfigOptions {
  /** Strict tool allowlist replacing the default tool set. */
  enabled?: string[] | null;

  /** Tools removed from the default tool set. */
  disabled?: string[] | null;
}

export interface NetworkConfigOptions {
  /** Request timeout in milliseconds. */
  timeout?: number;

  /** Maximum retries after a failed request. */
  maxRetries?: number;

  /** Allow private, loopback, or link-local artifact registries. */
  /** Security-sensitive SSRF escape hatch; opt in only for trusted enterprise registries. */
  allowPrivateRegistry?: boolean;
}

export interface LspConfigOptions {
  /** Optional path to a custom lsp-servers.json. */
  configPath?: string;
}

export interface OutputConfigOptions {
  /** Rendered response format. */
  format?: OutputFormat;

  /** Mask email addresses such as GitHub commit authors. */
  redactEmails?: boolean;

  pagination?: OutputPaginationConfigOptions;
}

export interface OutputPaginationConfigOptions {
  /** Automatic pagination character budget. */
  defaultCharLength?: number;
}

export interface StorageConfigOptions {
  /** Whether caches and runtime state may persist on disk. */
  mode?: StorageMode;
}

export interface ExtensionConfigOptions {
  storage?: ExtensionStorageConfigOptions;
}

export interface ExtensionStorageConfigOptions {
  /** Pi extension storage mode override. */
  mode?: StorageMode;
}

export interface JevConfigOptions {
  /** TypeSafe Jev API key fallback. */
  /** Never appears in ResolvedConfig; shell environment wins over the trusted home config file. */
  key?: string | null;

  /** Optional Jev model override. */
  model?: string | null;

  /** Optional trusted Jev API root. */
  /** Requires HTTP or HTTPS at config validation; provider policy may require HTTPS except loopback. */
  baseUrl?: string | null;
}

export interface OctocodeConfig {
  $schema?: string;

  /** Configuration schema version. */
  version?: number;

  github?: GitHubConfigOptions;

  local?: LocalConfigOptions;

  tools?: ToolsConfigOptions;

  network?: NetworkConfigOptions;

  lsp?: LspConfigOptions;

  output?: OutputConfigOptions;

  storage?: StorageConfigOptions;

  extension?: ExtensionConfigOptions;

  jev?: JevConfigOptions;
}

export interface RequiredGitHubConfig {
  apiUrl: string;
  graphqlEnabled: boolean;
}

export interface RequiredLocalConfig {
  enabled: boolean;
  enableClone: boolean;
  enableAstRewrite: boolean;
  enableAstRewriteApply: boolean;
  allowedPaths: string[];
  workspaceRoot: string | undefined;
}

export interface RequiredToolsConfig {
  enabled: string[] | null;
  disabled: string[] | null;
}

export interface RequiredNetworkConfig {
  timeout: number;
  maxRetries: number;
  allowPrivateRegistry: boolean;
}

export interface RequiredLspConfig {
  configPath: string | undefined;
}

export interface RequiredOutputConfig {
  format: OutputFormat;
  redactEmails: boolean;
  pagination: RequiredOutputPaginationConfig;
}

export interface RequiredOutputPaginationConfig {
  defaultCharLength: number;
}

export interface RequiredStorageConfig {
  mode: StorageMode;
}

export interface RequiredExtensionConfig {
  storage: RequiredExtensionStorageConfig;
}

export interface RequiredExtensionStorageConfig {
  mode: StorageMode;
}

export interface RequiredSessionConfig {
  enableStats: boolean;
}

export interface ResolvedConfigData {
  version: number;
  github: RequiredGitHubConfig;
  local: RequiredLocalConfig;
  tools: RequiredToolsConfig;
  network: RequiredNetworkConfig;
  lsp: RequiredLspConfig;
  output: RequiredOutputConfig;
  storage: RequiredStorageConfig;
  extension: RequiredExtensionConfig;
  session: RequiredSessionConfig;
}

export type ConfigFieldKind = 'boolean' | 'number' | 'string' | 'url' | 'path' | 'stringArray' | 'enum' | 'schemaVersion';
export interface ConfigEnvBinding {
  name: string;
  priority: number;
  dotenv?: 'all' | 'home' | 'never';
  normalize?: 'trim' | 'lower';
  invalid?: 'skip' | 'default';
}
export interface ConfigFieldSpec {
  path: string;
  section: string;
  key: string;
  type: ConfigFieldKind;
  file: boolean;
  resolved: boolean;
  credential: boolean;
  description: string;
  notes?: string;
  env: readonly ConfigEnvBinding[];
  defaultValue: unknown;
  defaultFrom?: string;
  minimum?: number;
  maximum?: number;
  values?: readonly string[];
  enumStyle?: 'list' | 'quotedOr';
  itemFormat?: 'path';
}

export const CONFIG_FIELDS: readonly ConfigFieldSpec[] = [
  {
    "path": "version",
    "section": "",
    "key": "version",
    "type": "schemaVersion",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Configuration schema version.",
    "env": [],
    "defaultValue": 1
  },
  {
    "path": "github.apiUrl",
    "section": "github",
    "key": "apiUrl",
    "type": "url",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "GitHub REST API root. GitHub Enterprise commonly uses /api/v3.",
    "env": [
      {
        "name": "GITHUB_API_URL",
        "priority": 0,
        "dotenv": "never",
        "normalize": "trim",
        "invalid": "skip"
      }
    ],
    "defaultValue": "https://api.github.com"
  },
  {
    "path": "github.graphqlEnabled",
    "section": "github",
    "key": "graphqlEnabled",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Use GitHub GraphQL where supported; false forces REST-only access.",
    "env": [
      {
        "name": "OCTOCODE_GITHUB_GRAPHQL",
        "priority": 0
      }
    ],
    "defaultValue": true
  },
  {
    "path": "local.enabled",
    "section": "local",
    "key": "enabled",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Enable local filesystem tools on every runtime surface.",
    "notes": "ENABLE_LOCAL is canonical; OCTOCODE_ENABLE_LOCAL is an alias.",
    "env": [
      {
        "name": "ENABLE_LOCAL",
        "priority": 0
      },
      {
        "name": "OCTOCODE_ENABLE_LOCAL",
        "priority": 1
      }
    ],
    "defaultValue": true
  },
  {
    "path": "local.enableClone",
    "section": "local",
    "key": "enableClone",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Enable ghCloneRepo and directory materialization.",
    "notes": "Opt-in and requires persistent storage. ENABLE_CLONE is canonical.",
    "env": [
      {
        "name": "ENABLE_CLONE",
        "priority": 0
      },
      {
        "name": "OCTOCODE_ENABLE_CLONE",
        "priority": 1
      }
    ],
    "defaultValue": false
  },
  {
    "path": "local.enableAstRewrite",
    "section": "local",
    "key": "enableAstRewrite",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Enable the astRewrite tool. Preview and apply are unavailable while false.",
    "env": [
      {
        "name": "ENABLE_AST_REWRITE",
        "priority": 0
      }
    ],
    "defaultValue": false
  },
  {
    "path": "local.enableAstRewriteApply",
    "section": "local",
    "key": "enableAstRewriteApply",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Permit hash-guarded astRewrite apply when astRewrite is enabled; preview remains available.",
    "env": [
      {
        "name": "ENABLE_AST_REWRITE_APPLY",
        "priority": 0
      }
    ],
    "defaultValue": false
  },
  {
    "path": "local.allowedPaths",
    "section": "local",
    "key": "allowedPaths",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Extra absolute or home-relative roots added to the allowed home directory.",
    "notes": "The environment value is a comma-separated list.",
    "env": [
      {
        "name": "ALLOWED_PATHS",
        "priority": 0
      }
    ],
    "defaultValue": [],
    "itemFormat": "path"
  },
  {
    "path": "local.workspaceRoot",
    "section": "local",
    "key": "workspaceRoot",
    "type": "path",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Optional absolute or home-relative workspace root.",
    "env": [
      {
        "name": "WORKSPACE_ROOT",
        "priority": 0,
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "tools.enabled",
    "section": "tools",
    "key": "enabled",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Strict tool allowlist replacing the default tool set.",
    "env": [
      {
        "name": "TOOLS_TO_RUN",
        "priority": 0
      }
    ],
    "defaultValue": null
  },
  {
    "path": "tools.disabled",
    "section": "tools",
    "key": "disabled",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Tools removed from the default tool set.",
    "env": [
      {
        "name": "DISABLE_TOOLS",
        "priority": 0
      }
    ],
    "defaultValue": null
  },
  {
    "path": "network.timeout",
    "section": "network",
    "key": "timeout",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Request timeout in milliseconds.",
    "env": [
      {
        "name": "REQUEST_TIMEOUT",
        "priority": 0
      }
    ],
    "defaultValue": 30000,
    "minimum": 5000,
    "maximum": 300000
  },
  {
    "path": "network.maxRetries",
    "section": "network",
    "key": "maxRetries",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Maximum retries after a failed request.",
    "env": [
      {
        "name": "MAX_RETRIES",
        "priority": 0
      }
    ],
    "defaultValue": 3,
    "minimum": 0,
    "maximum": 10
  },
  {
    "path": "network.allowPrivateRegistry",
    "section": "network",
    "key": "allowPrivateRegistry",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Allow private, loopback, or link-local artifact registries.",
    "notes": "Security-sensitive SSRF escape hatch; opt in only for trusted enterprise registries.",
    "env": [
      {
        "name": "OCTOCODE_ALLOW_PRIVATE_REGISTRY",
        "priority": 0,
        "dotenv": "never"
      }
    ],
    "defaultValue": false
  },
  {
    "path": "lsp.configPath",
    "section": "lsp",
    "key": "configPath",
    "type": "string",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Optional path to a custom lsp-servers.json.",
    "env": [
      {
        "name": "OCTOCODE_LSP_CONFIG",
        "priority": 0,
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "output.format",
    "section": "output",
    "key": "format",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Rendered response format.",
    "env": [
      {
        "name": "OCTOCODE_OUTPUT_FORMAT",
        "priority": 0,
        "normalize": "lower",
        "invalid": "default"
      }
    ],
    "defaultValue": "yaml",
    "values": [
      "yaml",
      "json"
    ]
  },
  {
    "path": "output.redactEmails",
    "section": "output",
    "key": "redactEmails",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Mask email addresses such as GitHub commit authors.",
    "env": [
      {
        "name": "OCTOCODE_REDACT_EMAILS",
        "priority": 0
      }
    ],
    "defaultValue": false
  },
  {
    "path": "output.pagination.defaultCharLength",
    "section": "output.pagination",
    "key": "defaultCharLength",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Automatic pagination character budget.",
    "env": [
      {
        "name": "OCTOCODE_OUTPUT_DEFAULT_CHAR_LENGTH",
        "priority": 0
      }
    ],
    "defaultValue": 20000,
    "minimum": 1000,
    "maximum": 50000
  },
  {
    "path": "storage.mode",
    "section": "storage",
    "key": "mode",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Whether caches and runtime state may persist on disk.",
    "env": [
      {
        "name": "OCTOCODE_STORAGE_MODE",
        "priority": 0,
        "normalize": "lower",
        "invalid": "skip"
      }
    ],
    "defaultValue": "persistent",
    "values": [
      "persistent",
      "memory"
    ],
    "enumStyle": "quotedOr"
  },
  {
    "path": "extension.storage.mode",
    "section": "extension.storage",
    "key": "mode",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Pi extension storage mode override.",
    "env": [
      {
        "name": "OCTOCODE_EXTENSION_STORAGE_MODE",
        "priority": 0,
        "normalize": "lower",
        "invalid": "skip"
      }
    ],
    "defaultValue": "persistent",
    "defaultFrom": "storage.mode",
    "values": [
      "persistent",
      "memory"
    ],
    "enumStyle": "quotedOr"
  },
  {
    "path": "jev.key",
    "section": "jev",
    "key": "key",
    "type": "string",
    "file": true,
    "resolved": false,
    "credential": true,
    "description": "TypeSafe Jev API key fallback.",
    "notes": "Never appears in ResolvedConfig; shell environment wins over the trusted home config file.",
    "env": [
      {
        "name": "OCTOCODE_JEV_KEY",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "jev.model",
    "section": "jev",
    "key": "model",
    "type": "string",
    "file": true,
    "resolved": false,
    "credential": true,
    "description": "Optional Jev model override.",
    "env": [
      {
        "name": "OCTOCODE_JEV_MODEL",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "jev.baseUrl",
    "section": "jev",
    "key": "baseUrl",
    "type": "url",
    "file": true,
    "resolved": false,
    "credential": true,
    "description": "Optional trusted Jev API root.",
    "notes": "Requires HTTP or HTTPS at config validation; provider policy may require HTTPS except loopback.",
    "env": [
      {
        "name": "OCTOCODE_JEV_BASE_URL",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "session.enableStats",
    "section": "session",
    "key": "enableStats",
    "type": "boolean",
    "file": false,
    "resolved": true,
    "credential": false,
    "description": "Write stats.json on flush; stats remain in memory either way.",
    "notes": "Environment-only setting.",
    "env": [
      {
        "name": "OCTOCODE_ENABLE_STATS",
        "priority": 0
      }
    ],
    "defaultValue": false
  }
];
export const CONFIG_SCHEMA_VERSION = 1;
export const CONFIG_FILE_NAME = ".octocoderc";
export const RUNTIME_SURFACES = ["mcp","cli"] as const;
export type RuntimeSurface = (typeof RUNTIME_SURFACES)[number];
export const DEFAULT_RUNTIME_SURFACE: RuntimeSurface = RUNTIME_SURFACES[0];
export const ENV_TOKEN_VARS = ["OCTOCODE_TOKEN","GH_TOKEN","GITHUB_TOKEN","GITHUB_PERSONAL_ACCESS_TOKEN"] as const;
export type EnvTokenVar = (typeof ENV_TOKEN_VARS)[number];
export const PROTECTED_KEY_NAMES = ["PATH","HOME","SHELL","USER","LOGNAME","PWD","TMPDIR","NODE_OPTIONS","PYTHON","GH_HOST","OCTOCODE_TOKEN","GH_TOKEN","GITHUB_TOKEN","GITHUB_PERSONAL_ACCESS_TOKEN","GITHUB_API_URL","OCTOCODE_ALLOW_PRIVATE_REGISTRY","OCTOCODE_JEV_KEY","OCTOCODE_JEV_MODEL","OCTOCODE_JEV_BASE_URL"] as const;
export const HOME_TRUSTED_ENV_KEYS = ["OCTOCODE_JEV_KEY","OCTOCODE_JEV_MODEL","OCTOCODE_JEV_BASE_URL"] as const;
export const CONFIG_SOURCE_ENV_KEYS = ["OCTOCODE_GITHUB_CLIENT_ID","GITHUB_API_URL","OCTOCODE_GITHUB_GRAPHQL","ENABLE_LOCAL","OCTOCODE_ENABLE_LOCAL","ENABLE_CLONE","OCTOCODE_ENABLE_CLONE","ENABLE_AST_REWRITE","ENABLE_AST_REWRITE_APPLY","ALLOWED_PATHS","WORKSPACE_ROOT","TOOLS_TO_RUN","DISABLE_TOOLS","REQUEST_TIMEOUT","MAX_RETRIES","OCTOCODE_ALLOW_PRIVATE_REGISTRY","OCTOCODE_LSP_CONFIG","OCTOCODE_OUTPUT_FORMAT","OCTOCODE_REDACT_EMAILS","OCTOCODE_OUTPUT_DEFAULT_CHAR_LENGTH","OCTOCODE_STORAGE_MODE","OCTOCODE_EXTENSION_STORAGE_MODE","OCTOCODE_JEV_KEY","OCTOCODE_JEV_MODEL","OCTOCODE_JEV_BASE_URL","OCTOCODE_ENABLE_STATS"] as const;
export type ConfigSourceEnvKey = (typeof CONFIG_SOURCE_ENV_KEYS)[number];
export const DEFAULT_CONFIG_VALUE: ResolvedConfigData = { "session": { "enableStats": false }, "storage": { "mode": "persistent" }, "output": { "pagination": { "defaultCharLength": 20000 }, "redactEmails": false, "format": "yaml" }, "lsp": { "configPath": undefined }, "network": { "allowPrivateRegistry": false, "maxRetries": 3, "timeout": 30000 }, "tools": { "disabled": null, "enabled": null }, "local": { "workspaceRoot": undefined, "allowedPaths": [], "enableAstRewriteApply": false, "enableAstRewrite": false, "enableClone": false, "enabled": true }, "github": { "graphqlEnabled": true, "apiUrl": "https://api.github.com" }, "version": 1, "extension": { "storage": { "mode": "persistent" } } };
export const DEFAULT_GITHUB_API_URL = "https://api.github.com" as const;
export const DEFAULT_GITHUB_GRAPHQL_ENABLED = true as const;
export const DEFAULT_LOCAL_ENABLED = true as const;
export const DEFAULT_LOCAL_ENABLE_CLONE = false as const;
export const DEFAULT_LOCAL_ENABLE_AST_REWRITE = false as const;
export const DEFAULT_LOCAL_ENABLE_AST_REWRITE_APPLY = false as const;
export const DEFAULT_LOCAL_ALLOWED_PATHS = [] as const;
export const DEFAULT_LOCAL_WORKSPACE_ROOT = null;
export const DEFAULT_TOOLS_ENABLED = null;
export const DEFAULT_TOOLS_DISABLED = null;
export const DEFAULT_NETWORK_TIMEOUT = 30000 as const;
export const MIN_TIMEOUT = 5000;
export const MAX_TIMEOUT = 300000;
export const DEFAULT_NETWORK_MAX_RETRIES = 3 as const;
export const MIN_RETRIES = 0;
export const MAX_RETRIES = 10;
export const DEFAULT_NETWORK_ALLOW_PRIVATE_REGISTRY = false as const;
export const DEFAULT_LSP_CONFIG_PATH = null;
export const DEFAULT_OUTPUT_FORMAT = "yaml" as const;
export const OUTPUT_FORMATS = ["yaml","json"] as const;
export const DEFAULT_OUTPUT_REDACT_EMAILS = false as const;
export const DEFAULT_OUTPUT_DEFAULT_CHAR_LENGTH = 20000 as const;
export const MIN_OUTPUT_DEFAULT_CHAR_LENGTH = 1000;
export const MAX_OUTPUT_DEFAULT_CHAR_LENGTH = 50000;
export const DEFAULT_STORAGE_MODE = "persistent" as const;
export const STORAGE_MODES = ["persistent","memory"] as const;
export const DEFAULT_SESSION_ENABLE_STATS = false as const;
