// @generated by scripts/generate-config-contract.ts from config-contract.json.
// Do not edit; run `yarn workspace @octocodeai/config generate:config-contract`.

export type OutputFormat = "yaml" | "json";
export type StorageMode = "persistent" | "memory";
export type ClassificationVendor = "jev";

export interface GitHubConfigOptions {
  /** GitHub REST API root. GitHub Enterprise commonly uses /api/v3. */
  apiUrl?: string;

  /** Use GitHub GraphQL where supported; false forces REST-only access. */
  graphqlEnabled?: boolean;
}

export interface LocalConfigOptions {
  /** Enable local filesystem tools on every runtime surface. */
  enabled?: boolean;

  /** Enable beta features and tools; off by default on every surface. `octocode schema` reports which tools the gate withholds. */
  beta?: boolean;

  /** Extra absolute or home-relative roots added to the allowed roots (workspace root and OCTOCODE_HOME). */
  /** The environment value is a comma-separated list. */
  allowedPaths?: string[];

  /** Optional absolute or home-relative workspace root. */
  workspaceRoot?: string;
}

export interface ToolsConfigOptions {
  /** Strict tool allowlist replacing the default tool set. */
  enabled?: string[] | null;

  /** Tools removed from the default tool set. */
  disabled?: string[] | null;
}

export interface McpConfigOptions {
  /** Available tools left out of tools/list; one run({tool, query}) tool executes them and next/hints leads that name them. */
  deferred?: string[] | null;
}

export interface NetworkConfigOptions {
  /** Request timeout in milliseconds. */
  timeout?: number;

  /** Maximum retries after a failed request. */
  maxRetries?: number;

  /** Allow private, loopback, or link-local artifact registries. */
  /** Security-sensitive SSRF escape hatch; opt in only for trusted enterprise registries. */
  allowPrivateRegistry?: boolean;
}

export interface LspConfigOptions {
  /** Optional path to a custom lsp-servers.json. */
  configPath?: string;

  /** Whether `octocode lsp-server install` may download a managed language server: prompt (ask), off, or auto. */
  autoInstall?: "prompt" | "off" | "auto";

  /** Directory for managed language-server installs; default <octocode home>/lsp. */
  cacheDir?: string;

  /** Trust a project .octocode/lsp-servers.json. Security-sensitive: a trusted project config can launch server binaries. */
  trustProjectConfig?: boolean;

  /** Language-server prewarm: targeted starts the server an offered lspSearch call names; all also warms the file a read or search names; off disables it. */
  prewarm?: "targeted" | "all" | "off";
}

export interface OutputConfigOptions {
  /** Encoding of rendered text content (the MCP text channel): yaml or json. Structured content and CLI stdout are always JSON. */
  format?: OutputFormat;

  /** Mask email addresses such as GitHub commit authors. */
  redactEmails?: boolean;

  pagination?: OutputPaginationConfigOptions;
}

export interface OutputPaginationConfigOptions {
  /** Automatic pagination character budget. */
  defaultCharLength?: number;
}

export interface StorageConfigOptions {
  /** Whether caches and runtime state may persist on disk. */
  mode?: StorageMode;

  /** Write stats.json on flush; stats remain in memory either way. */
  stats?: boolean;

  cloneCache?: StorageCloneCacheConfigOptions;
}

export interface StorageCloneCacheConfigOptions {
  /** Milliseconds a ghCloneRepo checkout stays fresh before it is re-fetched. */
  ttl?: number;

  /** Byte cap for the on-disk ghCloneRepo cache; least-recently-used checkouts are evicted above it. */
  maxSize?: number;

  /** Maximum repositories the ghCloneRepo cache keeps. */
  maxClones?: number;
}

export interface ClassificationConfigOptions {
  /** Classification vendor. Per-vendor defaults (host, model, endpoint) are built in. */
  type?: ClassificationVendor;

  /** Classification provider API key (bearer credential). */
  /** Never appears in ResolvedConfig; shell environment wins over the trusted home config file. */
  api?: string | null;

  /** Optional override of the selected vendor's default API root. */
  /** Requires HTTP or HTTPS at config validation; provider policy may require HTTPS except loopback. */
  apiHost?: string | null;

  /** Process-wide maximum in-flight classification provider requests per provider endpoint. */
  maxConcurrency?: number;
}

export interface OctocodeConfig {
  $schema?: string;

  /** Configuration schema version. */
  version?: number;

  github?: GitHubConfigOptions;

  local?: LocalConfigOptions;

  tools?: ToolsConfigOptions;

  mcp?: McpConfigOptions;

  network?: NetworkConfigOptions;

  lsp?: LspConfigOptions;

  output?: OutputConfigOptions;

  storage?: StorageConfigOptions;

  classification?: ClassificationConfigOptions;
}

export interface RequiredGitHubConfig {
  apiUrl: string;
  graphqlEnabled: boolean;
}

export interface RequiredLocalConfig {
  enabled: boolean;
  beta: boolean;
  allowedPaths: string[];
  workspaceRoot: string | undefined;
}

export interface RequiredToolsConfig {
  enabled: string[] | null;
  disabled: string[] | null;
}

export interface RequiredMcpConfig {
  deferred: string[] | null;
}

export interface RequiredNetworkConfig {
  timeout: number;
  maxRetries: number;
  allowPrivateRegistry: boolean;
}

export interface RequiredLspConfig {
  configPath: string | undefined;
  autoInstall: "prompt" | "off" | "auto";
  cacheDir: string | undefined;
  trustProjectConfig: boolean;
  prewarm: "targeted" | "all" | "off";
}

export interface RequiredOutputConfig {
  format: OutputFormat;
  redactEmails: boolean;
  pagination: RequiredOutputPaginationConfig;
}

export interface RequiredOutputPaginationConfig {
  defaultCharLength: number;
}

export interface RequiredStorageConfig {
  mode: StorageMode;
  stats: boolean;
  cloneCache: RequiredStorageCloneCacheConfig;
}

export interface RequiredStorageCloneCacheConfig {
  ttl: number;
  maxSize: number;
  maxClones: number;
}

export interface RequiredClassificationConfig {
  type: ClassificationVendor;
  maxConcurrency: number;
}

export interface ResolvedConfigData {
  version: number;
  github: RequiredGitHubConfig;
  local: RequiredLocalConfig;
  tools: RequiredToolsConfig;
  mcp: RequiredMcpConfig;
  network: RequiredNetworkConfig;
  lsp: RequiredLspConfig;
  output: RequiredOutputConfig;
  storage: RequiredStorageConfig;
  classification: RequiredClassificationConfig;
}

export type ConfigFieldKind = 'boolean' | 'number' | 'string' | 'url' | 'path' | 'stringArray' | 'enum' | 'schemaVersion';
export interface ConfigEnvBinding {
  name: string;
  priority: number;
  dotenv?: 'all' | 'home' | 'never';
  normalize?: 'trim' | 'lower';
  invalid?: 'skip' | 'default';
  workspaceNarrowsTo?: string;
}
export interface ConfigFieldSpec {
  path: string;
  section: string;
  key: string;
  type: ConfigFieldKind;
  file: boolean;
  resolved: boolean;
  credential: boolean;
  description: string;
  notes?: string;
  env: readonly ConfigEnvBinding[];
  defaultValue: unknown;
  minimum?: number;
  maximum?: number;
  values?: readonly string[];
  enumStyle?: 'list' | 'quotedOr';
  itemFormat?: 'path';
}

export const CONFIG_FIELDS: readonly ConfigFieldSpec[] = [
  {
    "path": "version",
    "section": "",
    "key": "version",
    "type": "schemaVersion",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Configuration schema version.",
    "env": [],
    "defaultValue": 1
  },
  {
    "path": "github.apiUrl",
    "section": "github",
    "key": "apiUrl",
    "type": "url",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "GitHub REST API root. GitHub Enterprise commonly uses /api/v3.",
    "env": [
      {
        "name": "GITHUB_API_URL",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim",
        "invalid": "skip"
      }
    ],
    "defaultValue": "https://api.github.com"
  },
  {
    "path": "github.graphqlEnabled",
    "section": "github",
    "key": "graphqlEnabled",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Use GitHub GraphQL where supported; false forces REST-only access.",
    "env": [
      {
        "name": "OCTOCODE_GITHUB_GRAPHQL",
        "priority": 0
      }
    ],
    "defaultValue": true
  },
  {
    "path": "local.enabled",
    "section": "local",
    "key": "enabled",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Enable local filesystem tools on every runtime surface.",
    "env": [
      {
        "name": "OCTOCODE_ENABLE_LOCAL",
        "priority": 0
      }
    ],
    "defaultValue": true
  },
  {
    "path": "local.beta",
    "section": "local",
    "key": "beta",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Enable beta features and tools; off by default on every surface. `octocode schema` reports which tools the gate withholds.",
    "env": [
      {
        "name": "OCTOCODE_BETA",
        "priority": 0,
        "dotenv": "home"
      }
    ],
    "defaultValue": false
  },
  {
    "path": "local.allowedPaths",
    "section": "local",
    "key": "allowedPaths",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Extra absolute or home-relative roots added to the allowed roots (workspace root and OCTOCODE_HOME).",
    "notes": "The environment value is a comma-separated list.",
    "env": [
      {
        "name": "ALLOWED_PATHS",
        "priority": 0,
        "dotenv": "home"
      }
    ],
    "defaultValue": [],
    "itemFormat": "path"
  },
  {
    "path": "local.workspaceRoot",
    "section": "local",
    "key": "workspaceRoot",
    "type": "path",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Optional absolute or home-relative workspace root.",
    "env": [
      {
        "name": "WORKSPACE_ROOT",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "tools.enabled",
    "section": "tools",
    "key": "enabled",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Strict tool allowlist replacing the default tool set.",
    "env": [
      {
        "name": "TOOLS_TO_RUN",
        "priority": 0
      }
    ],
    "defaultValue": null
  },
  {
    "path": "tools.disabled",
    "section": "tools",
    "key": "disabled",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Tools removed from the default tool set.",
    "env": [
      {
        "name": "DISABLE_TOOLS",
        "priority": 0
      }
    ],
    "defaultValue": null
  },
  {
    "path": "mcp.deferred",
    "section": "mcp",
    "key": "deferred",
    "type": "stringArray",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Available tools left out of tools/list; one run({tool, query}) tool executes them and next/hints leads that name them.",
    "env": [
      {
        "name": "OCTOCODE_DEFER_TOOLS",
        "priority": 0
      }
    ],
    "defaultValue": null
  },
  {
    "path": "network.timeout",
    "section": "network",
    "key": "timeout",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Request timeout in milliseconds.",
    "env": [
      {
        "name": "REQUEST_TIMEOUT",
        "priority": 0
      }
    ],
    "defaultValue": 30000,
    "minimum": 5000,
    "maximum": 300000
  },
  {
    "path": "network.maxRetries",
    "section": "network",
    "key": "maxRetries",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Maximum retries after a failed request.",
    "env": [
      {
        "name": "MAX_RETRIES",
        "priority": 0
      }
    ],
    "defaultValue": 3,
    "minimum": 0,
    "maximum": 10
  },
  {
    "path": "network.allowPrivateRegistry",
    "section": "network",
    "key": "allowPrivateRegistry",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Allow private, loopback, or link-local artifact registries.",
    "notes": "Security-sensitive SSRF escape hatch; opt in only for trusted enterprise registries.",
    "env": [
      {
        "name": "OCTOCODE_ALLOW_PRIVATE_REGISTRY",
        "priority": 0,
        "dotenv": "home"
      }
    ],
    "defaultValue": false
  },
  {
    "path": "lsp.configPath",
    "section": "lsp",
    "key": "configPath",
    "type": "string",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Optional path to a custom lsp-servers.json.",
    "env": [
      {
        "name": "OCTOCODE_LSP_CONFIG",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "lsp.autoInstall",
    "section": "lsp",
    "key": "autoInstall",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Whether `octocode lsp-server install` may download a managed language server: prompt (ask), off, or auto.",
    "env": [
      {
        "name": "OCTOCODE_LSP_AUTO_INSTALL",
        "priority": 0,
        "dotenv": "home",
        "normalize": "lower",
        "invalid": "skip"
      }
    ],
    "defaultValue": "prompt",
    "values": [
      "prompt",
      "off",
      "auto"
    ]
  },
  {
    "path": "lsp.cacheDir",
    "section": "lsp",
    "key": "cacheDir",
    "type": "path",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Directory for managed language-server installs; default <octocode home>/lsp.",
    "env": [
      {
        "name": "OCTOCODE_LSP_CACHE_DIR",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "lsp.trustProjectConfig",
    "section": "lsp",
    "key": "trustProjectConfig",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Trust a project .octocode/lsp-servers.json. Security-sensitive: a trusted project config can launch server binaries.",
    "env": [
      {
        "name": "OCTOCODE_TRUST_PROJECT_LSP_CONFIG",
        "priority": 0,
        "dotenv": "home"
      }
    ],
    "defaultValue": false
  },
  {
    "path": "lsp.prewarm",
    "section": "lsp",
    "key": "prewarm",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Language-server prewarm: targeted starts the server an offered lspSearch call names; all also warms the file a read or search names; off disables it.",
    "env": [
      {
        "name": "OCTOCODE_LSP_PREWARM",
        "priority": 0,
        "normalize": "lower",
        "invalid": "skip"
      }
    ],
    "defaultValue": "targeted",
    "values": [
      "targeted",
      "all",
      "off"
    ]
  },
  {
    "path": "output.format",
    "section": "output",
    "key": "format",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Encoding of rendered text content (the MCP text channel): yaml or json. Structured content and CLI stdout are always JSON.",
    "env": [
      {
        "name": "OCTOCODE_OUTPUT_FORMAT",
        "priority": 0,
        "normalize": "lower",
        "invalid": "default"
      }
    ],
    "defaultValue": "yaml",
    "values": [
      "yaml",
      "json"
    ]
  },
  {
    "path": "output.redactEmails",
    "section": "output",
    "key": "redactEmails",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Mask email addresses such as GitHub commit authors.",
    "env": [
      {
        "name": "OCTOCODE_REDACT_EMAILS",
        "priority": 0
      }
    ],
    "defaultValue": false
  },
  {
    "path": "output.pagination.defaultCharLength",
    "section": "output.pagination",
    "key": "defaultCharLength",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Automatic pagination character budget.",
    "env": [
      {
        "name": "OCTOCODE_OUTPUT_DEFAULT_CHAR_LENGTH",
        "priority": 0
      }
    ],
    "defaultValue": 50000,
    "minimum": 1000,
    "maximum": 50000
  },
  {
    "path": "storage.mode",
    "section": "storage",
    "key": "mode",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Whether caches and runtime state may persist on disk.",
    "env": [
      {
        "name": "OCTOCODE_STORAGE_MODE",
        "priority": 0,
        "dotenv": "home",
        "normalize": "lower",
        "invalid": "skip",
        "workspaceNarrowsTo": "memory"
      }
    ],
    "defaultValue": "persistent",
    "values": [
      "persistent",
      "memory"
    ],
    "enumStyle": "quotedOr"
  },
  {
    "path": "storage.stats",
    "section": "storage",
    "key": "stats",
    "type": "boolean",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Write stats.json on flush; stats remain in memory either way.",
    "env": [
      {
        "name": "OCTOCODE_ENABLE_STATS",
        "priority": 0
      }
    ],
    "defaultValue": false
  },
  {
    "path": "storage.cloneCache.ttl",
    "section": "storage.cloneCache",
    "key": "ttl",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Milliseconds a ghCloneRepo checkout stays fresh before it is re-fetched.",
    "env": [
      {
        "name": "OCTOCODE_CACHE_TTL_MS",
        "priority": 0
      }
    ],
    "defaultValue": 86400000,
    "minimum": 60000,
    "maximum": 2592000000
  },
  {
    "path": "storage.cloneCache.maxSize",
    "section": "storage.cloneCache",
    "key": "maxSize",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Byte cap for the on-disk ghCloneRepo cache; least-recently-used checkouts are evicted above it.",
    "env": [
      {
        "name": "OCTOCODE_MAX_CACHE_SIZE",
        "priority": 0
      }
    ],
    "defaultValue": 2147483648,
    "minimum": 1048576,
    "maximum": 1099511627776
  },
  {
    "path": "storage.cloneCache.maxClones",
    "section": "storage.cloneCache",
    "key": "maxClones",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Maximum repositories the ghCloneRepo cache keeps.",
    "env": [
      {
        "name": "OCTOCODE_MAX_CLONES",
        "priority": 0
      }
    ],
    "defaultValue": 50,
    "minimum": 1,
    "maximum": 1000
  },
  {
    "path": "classification.type",
    "section": "classification",
    "key": "type",
    "type": "enum",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Classification vendor. Per-vendor defaults (host, model, endpoint) are built in.",
    "env": [
      {
        "name": "OCTOCODE_CLASSIFICATION_TYPE",
        "priority": 0,
        "dotenv": "all",
        "normalize": "trim",
        "invalid": "skip"
      }
    ],
    "defaultValue": "jev",
    "values": [
      "jev"
    ],
    "enumStyle": "quotedOr"
  },
  {
    "path": "classification.api",
    "section": "classification",
    "key": "api",
    "type": "string",
    "file": true,
    "resolved": false,
    "credential": true,
    "description": "Classification provider API key (bearer credential).",
    "notes": "Never appears in ResolvedConfig; shell environment wins over the trusted home config file.",
    "env": [
      {
        "name": "OCTOCODE_CLASSIFICATION_API",
        "priority": 0,
        "dotenv": "all",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "classification.apiHost",
    "section": "classification",
    "key": "apiHost",
    "type": "url",
    "file": true,
    "resolved": false,
    "credential": true,
    "description": "Optional override of the selected vendor's default API root.",
    "notes": "Requires HTTP or HTTPS at config validation; provider policy may require HTTPS except loopback.",
    "env": [
      {
        "name": "OCTOCODE_CLASSIFICATION_API_HOST",
        "priority": 0,
        "dotenv": "home",
        "normalize": "trim"
      }
    ],
    "defaultValue": null
  },
  {
    "path": "classification.maxConcurrency",
    "section": "classification",
    "key": "maxConcurrency",
    "type": "number",
    "file": true,
    "resolved": true,
    "credential": false,
    "description": "Process-wide maximum in-flight classification provider requests per provider endpoint.",
    "env": [
      {
        "name": "OCTOCODE_CLASSIFICATION_CONCURRENCY",
        "priority": 0
      }
    ],
    "defaultValue": 10,
    "minimum": 1,
    "maximum": 64
  }
];
export const CONFIG_SCHEMA_VERSION = 1;
export const CONFIG_FILE_NAME = ".octocoderc";
export const RUNTIME_SURFACES = ["mcp","cli"] as const;
export type RuntimeSurface = (typeof RUNTIME_SURFACES)[number];
export const DEFAULT_RUNTIME_SURFACE: RuntimeSurface = RUNTIME_SURFACES[0];
export const ENV_TOKEN_VARS = ["GH_TOKEN","GITHUB_TOKEN"] as const;
export type EnvTokenVar = (typeof ENV_TOKEN_VARS)[number];
export const PROTECTED_KEY_NAMES = ["PATH","HOME","SHELL","USER","LOGNAME","PWD","TMPDIR","NODE_OPTIONS","PYTHON","OCTOCODE_HOME","OCTOCODE_CARGO","GITHUB_API_URL","OCTOCODE_BETA","ALLOWED_PATHS","WORKSPACE_ROOT","OCTOCODE_ALLOW_PRIVATE_REGISTRY","OCTOCODE_LSP_CONFIG","OCTOCODE_LSP_AUTO_INSTALL","OCTOCODE_LSP_CACHE_DIR","OCTOCODE_TRUST_PROJECT_LSP_CONFIG","OCTOCODE_STORAGE_MODE","OCTOCODE_CLASSIFICATION_API_HOST"] as const;
export const HOME_TRUSTED_ENV_KEYS = ["OCTOCODE_CARGO","GITHUB_API_URL","OCTOCODE_BETA","ALLOWED_PATHS","WORKSPACE_ROOT","OCTOCODE_ALLOW_PRIVATE_REGISTRY","OCTOCODE_LSP_CONFIG","OCTOCODE_LSP_AUTO_INSTALL","OCTOCODE_LSP_CACHE_DIR","OCTOCODE_TRUST_PROJECT_LSP_CONFIG","OCTOCODE_STORAGE_MODE","OCTOCODE_CLASSIFICATION_API_HOST"] as const;
/** Home-trusted switches a workspace may set only to this narrowing value. */
export const WORKSPACE_NARROW_ONLY_ENV: Readonly<Record<string, string>> = {"OCTOCODE_STORAGE_MODE":"memory"};
export const CONFIG_SOURCE_ENV_KEYS = ["OCTOCODE_GITHUB_CLIENT_ID","GITHUB_API_URL","OCTOCODE_GITHUB_GRAPHQL","OCTOCODE_ENABLE_LOCAL","OCTOCODE_BETA","ALLOWED_PATHS","WORKSPACE_ROOT","TOOLS_TO_RUN","DISABLE_TOOLS","OCTOCODE_DEFER_TOOLS","REQUEST_TIMEOUT","MAX_RETRIES","OCTOCODE_ALLOW_PRIVATE_REGISTRY","OCTOCODE_LSP_CONFIG","OCTOCODE_LSP_AUTO_INSTALL","OCTOCODE_LSP_CACHE_DIR","OCTOCODE_TRUST_PROJECT_LSP_CONFIG","OCTOCODE_LSP_PREWARM","OCTOCODE_OUTPUT_FORMAT","OCTOCODE_REDACT_EMAILS","OCTOCODE_OUTPUT_DEFAULT_CHAR_LENGTH","OCTOCODE_STORAGE_MODE","OCTOCODE_ENABLE_STATS","OCTOCODE_CACHE_TTL_MS","OCTOCODE_MAX_CACHE_SIZE","OCTOCODE_MAX_CLONES","OCTOCODE_CLASSIFICATION_TYPE","OCTOCODE_CLASSIFICATION_API","OCTOCODE_CLASSIFICATION_API_HOST","OCTOCODE_CLASSIFICATION_CONCURRENCY"] as const;
export type ConfigSourceEnvKey = (typeof CONFIG_SOURCE_ENV_KEYS)[number];
export const DEFAULT_CONFIG_VALUE: ResolvedConfigData = { "version": 1, "github": { "apiUrl": "https://api.github.com", "graphqlEnabled": true }, "local": { "enabled": true, "beta": false, "allowedPaths": [], "workspaceRoot": undefined }, "tools": { "enabled": null, "disabled": null }, "mcp": { "deferred": null }, "network": { "timeout": 30000, "maxRetries": 3, "allowPrivateRegistry": false }, "lsp": { "configPath": undefined, "autoInstall": "prompt", "cacheDir": undefined, "trustProjectConfig": false, "prewarm": "targeted" }, "output": { "format": "yaml", "redactEmails": false, "pagination": { "defaultCharLength": 50000 } }, "storage": { "mode": "persistent", "stats": false, "cloneCache": { "ttl": 86400000, "maxSize": 2147483648, "maxClones": 50 } }, "classification": { "type": "jev", "maxConcurrency": 10 } };
export const DEFAULT_GITHUB_API_URL = "https://api.github.com" as const;
export const DEFAULT_GITHUB_GRAPHQL_ENABLED = true as const;
export const DEFAULT_LOCAL_ENABLED = true as const;
export const DEFAULT_LOCAL_BETA = false as const;
export const DEFAULT_LOCAL_ALLOWED_PATHS = [] as const;
export const DEFAULT_LOCAL_WORKSPACE_ROOT = null;
export const DEFAULT_TOOLS_ENABLED = null;
export const DEFAULT_TOOLS_DISABLED = null;
export const DEFAULT_MCP_DEFERRED = null;
export const DEFAULT_NETWORK_TIMEOUT = 30000 as const;
export const MIN_TIMEOUT = 5000;
export const MAX_TIMEOUT = 300000;
export const DEFAULT_NETWORK_MAX_RETRIES = 3 as const;
export const MIN_RETRIES = 0;
export const MAX_RETRIES = 10;
export const DEFAULT_NETWORK_ALLOW_PRIVATE_REGISTRY = false as const;
export const DEFAULT_LSP_CONFIG_PATH = null;
export const DEFAULT_LSP_AUTO_INSTALL = "prompt" as const;
export const DEFAULT_LSP_CACHE_DIR = null;
export const DEFAULT_LSP_TRUST_PROJECT_CONFIG = false as const;
export const DEFAULT_LSP_PREWARM = "targeted" as const;
export const DEFAULT_OUTPUT_FORMAT = "yaml" as const;
export const OUTPUT_FORMATS = ["yaml","json"] as const;
export const DEFAULT_OUTPUT_REDACT_EMAILS = false as const;
export const DEFAULT_OUTPUT_DEFAULT_CHAR_LENGTH = 50000 as const;
export const MIN_OUTPUT_DEFAULT_CHAR_LENGTH = 1000;
export const MAX_OUTPUT_DEFAULT_CHAR_LENGTH = 50000;
export const DEFAULT_STORAGE_MODE = "persistent" as const;
export const STORAGE_MODES = ["persistent","memory"] as const;
export const DEFAULT_STORAGE_STATS = false as const;
export const DEFAULT_CLONE_CACHE_TTL = 86400000 as const;
export const MIN_CLONE_CACHE_TTL = 60000;
export const MAX_CLONE_CACHE_TTL = 2592000000;
export const DEFAULT_CLONE_CACHE_MAX_SIZE = 2147483648 as const;
export const MIN_CLONE_CACHE_MAX_SIZE = 1048576;
export const MAX_CLONE_CACHE_MAX_SIZE = 1099511627776;
export const DEFAULT_CLONE_CACHE_MAX_CLONES = 50 as const;
export const MIN_CLONE_CACHE_MAX_CLONES = 1;
export const MAX_CLONE_CACHE_MAX_CLONES = 1000;
export const DEFAULT_CLASSIFICATION_TYPE = "jev" as const;
export const CLASSIFICATION_VENDORS = ["jev"] as const;
export const DEFAULT_CLASSIFICATION_MAX_CONCURRENCY = 10 as const;
export const MIN_CLASSIFICATION_CONCURRENCY = 1;
export const MAX_CLASSIFICATION_CONCURRENCY = 64;
