import {
  DEFAULT_CONFIG_VALUE,
  DEFAULT_GITHUB_API_URL,
  DEFAULT_GITHUB_GRAPHQL_ENABLED,
  DEFAULT_LOCAL_ENABLED,
  DEFAULT_LOCAL_BETA,
  DEFAULT_NETWORK_ALLOW_PRIVATE_REGISTRY,
  DEFAULT_NETWORK_MAX_RETRIES,
  DEFAULT_NETWORK_TIMEOUT,
  DEFAULT_OUTPUT_DEFAULT_CHAR_LENGTH,
  DEFAULT_OUTPUT_FORMAT,
  DEFAULT_OUTPUT_REDACT_EMAILS,
  DEFAULT_SESSION_ENABLE_STATS,
  DEFAULT_STORAGE_MODE,
  MAX_OUTPUT_DEFAULT_CHAR_LENGTH,
  MAX_RETRIES,
  MAX_TIMEOUT,
  MIN_OUTPUT_DEFAULT_CHAR_LENGTH,
  MIN_RETRIES,
  MIN_TIMEOUT,
} from './contract.generated.js';

export {
  DEFAULT_GITHUB_API_URL,
  DEFAULT_GITHUB_GRAPHQL_ENABLED,
  DEFAULT_LOCAL_ENABLED,
  DEFAULT_LOCAL_BETA,
  DEFAULT_NETWORK_ALLOW_PRIVATE_REGISTRY,
  DEFAULT_NETWORK_MAX_RETRIES,
  DEFAULT_NETWORK_TIMEOUT,
  DEFAULT_OUTPUT_DEFAULT_CHAR_LENGTH,
  DEFAULT_OUTPUT_FORMAT,
  DEFAULT_OUTPUT_REDACT_EMAILS,
  DEFAULT_SESSION_ENABLE_STATS,
  DEFAULT_STORAGE_MODE,
  MAX_OUTPUT_DEFAULT_CHAR_LENGTH,
  MAX_RETRIES,
  MAX_TIMEOUT,
  MIN_OUTPUT_DEFAULT_CHAR_LENGTH,
  MIN_RETRIES,
  MIN_TIMEOUT,
};

export const DEFAULT_GITHUB_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.github);
export const DEFAULT_LOCAL_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.local);
export const DEFAULT_TOOLS_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.tools);
export const DEFAULT_NETWORK_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.network);
export const DEFAULT_LSP_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.lsp);
export const DEFAULT_OUTPUT_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.output);
export const DEFAULT_SESSION_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.session);
export const DEFAULT_STORAGE_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE.storage);

export const DEFAULT_CONFIG = Object.freeze(DEFAULT_CONFIG_VALUE);
