// @generated by scripts/generate-shared-constants.ts from shared-constants.json.
// Do not edit; run `yarn workspace @octocodeai/config generate:shared-constants`.

export const SHARED_CONSTANTS = {
  "configSchemaVersion": 1,
  "configFileName": ".octocoderc",
  "runtimeSurfaces": [
    "cli",
    "mcp"
  ],
  "runtimeSurfaceDefault": "mcp",
  "envTokenVars": [
    "OCTOCODE_TOKEN",
    "GH_TOKEN",
    "GITHUB_TOKEN",
    "GITHUB_PERSONAL_ACCESS_TOKEN"
  ],
  "protectedKeys": [
    "PATH",
    "HOME",
    "SHELL",
    "USER",
    "LOGNAME",
    "PWD",
    "TMPDIR",
    "NODE_OPTIONS",
    "OCTOCODE_TOKEN",
    "GH_TOKEN",
    "GITHUB_TOKEN",
    "GITHUB_PERSONAL_ACCESS_TOKEN",
    "PYTHON",
    "GITHUB_API_URL",
    "GH_HOST",
    "OCTOCODE_ALLOW_PRIVATE_REGISTRY",
    "OCTOCODE_JEV_KEY",
    "OCTOCODE_JEV_BASE_URL",
    "OCTOCODE_JEV_MODEL"
  ],
  "configSourceEnvKeys": [
    "GITHUB_API_URL",
    "OCTOCODE_GITHUB_CLIENT_ID",
    "OCTOCODE_GITHUB_GRAPHQL",
    "ENABLE_LOCAL",
    "OCTOCODE_ENABLE_LOCAL",
    "ENABLE_CLONE",
    "OCTOCODE_ENABLE_CLONE",
    "ENABLE_AST_REWRITE_APPLY",
    "ALLOWED_PATHS",
    "WORKSPACE_ROOT",
    "TOOLS_TO_RUN",
    "DISABLE_TOOLS",
    "REQUEST_TIMEOUT",
    "MAX_RETRIES",
    "OCTOCODE_ALLOW_PRIVATE_REGISTRY",
    "OCTOCODE_LSP_CONFIG",
    "OCTOCODE_OUTPUT_FORMAT",
    "OCTOCODE_OUTPUT_DEFAULT_CHAR_LENGTH",
    "OCTOCODE_REDACT_EMAILS",
    "OCTOCODE_ENABLE_STATS",
    "OCTOCODE_STORAGE_MODE",
    "OCTOCODE_EXTENSION_STORAGE_MODE",
    "OCTOCODE_JEV_KEY",
    "OCTOCODE_JEV_MODEL",
    "OCTOCODE_JEV_BASE_URL"
  ],
  "validationBounds": {
    "minTimeout": 5000,
    "maxTimeout": 300000,
    "minRetries": 0,
    "maxRetries": 10,
    "minOutputDefaultCharLength": 1000,
    "maxOutputDefaultCharLength": 50000
  }
} as const;

export const CONFIG_SCHEMA_VERSION = SHARED_CONSTANTS.configSchemaVersion;
export const CONFIG_FILE_NAME = SHARED_CONSTANTS.configFileName;
export const RUNTIME_SURFACES = SHARED_CONSTANTS.runtimeSurfaces;
export type RuntimeSurface = (typeof RUNTIME_SURFACES)[number];
export const DEFAULT_RUNTIME_SURFACE: RuntimeSurface = SHARED_CONSTANTS.runtimeSurfaceDefault;
export const ENV_TOKEN_VARS = SHARED_CONSTANTS.envTokenVars;
export type EnvTokenVar = (typeof ENV_TOKEN_VARS)[number];
export const PROTECTED_KEY_NAMES = SHARED_CONSTANTS.protectedKeys;
export const CONFIG_SOURCE_ENV_KEYS = SHARED_CONSTANTS.configSourceEnvKeys;
export type ConfigSourceEnvKey = (typeof CONFIG_SOURCE_ENV_KEYS)[number];
export const VALIDATION_BOUNDS = SHARED_CONSTANTS.validationBounds;
export const MIN_TIMEOUT = VALIDATION_BOUNDS.minTimeout;
export const MAX_TIMEOUT = VALIDATION_BOUNDS.maxTimeout;
export const MIN_RETRIES = VALIDATION_BOUNDS.minRetries;
export const MAX_RETRIES = VALIDATION_BOUNDS.maxRetries;
export const MIN_OUTPUT_DEFAULT_CHAR_LENGTH = VALIDATION_BOUNDS.minOutputDefaultCharLength;
export const MAX_OUTPUT_DEFAULT_CHAR_LENGTH = VALIDATION_BOUNDS.maxOutputDefaultCharLength;
