//! Canonical tool identity.
//!
//! `ToolId`, its wire names, family, CLI-only and beta policy are generated by
//! build.rs from the embedded contract (core `TOOL_POLICIES`); this module only
//! adds runtime-owned behavior on top.

use std::str::FromStr;

/// Family used to partition cursor scope digests and remote/local policy.
///
/// Toggling local-only config (e.g. `allowed_paths`) must not invalidate
/// GitHub/remote cursors, so each family scopes its digest differently.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ToolFamily {
    /// Local-filesystem tools: scoped by cwd, allowed paths, and LSP config.
    Local,
    /// GitHub API tools: scoped by API endpoint + home, not local config.
    GitHub,
    /// Other remote tools (artifact, clasify): scoped by home only.
    Remote,
}

include!(concat!(env!("OUT_DIR"), "/tool_ids.rs"));

impl ToolId {
    /// Resolve a wire name to its identity, or `None` for an unknown tool.
    #[must_use]
    pub fn from_name(name: &str) -> Option<ToolId> {
        ToolId::ALL.into_iter().find(|id| id.as_str() == name)
    }

    /// A local-filesystem tool (honours local policy + allowed paths).
    #[must_use]
    pub const fn is_local(self) -> bool {
        matches!(self.family(), ToolFamily::Local)
    }

    /// A GitHub API tool (includes `ghCloneRepo`; clone has an extra gate).
    #[must_use]
    pub const fn is_github(self) -> bool {
        matches!(self.family(), ToolFamily::GitHub)
    }

    /// A semantic assessment tool (gated on a non-blank `OCTOCODE_CLASSIFICATION_API`
    /// or the selected vendor's native key, e.g. `OCTOCODE_JEV_KEY`).
    #[must_use]
    pub const fn is_clasify(self) -> bool {
        matches!(self, ToolId::Clasify)
    }

    /// Independent read-only queries may execute concurrently. Mutating clone
    /// and rewrite operations remain ordered; clasify owns its own bounded
    /// provider scheduler.
    #[must_use]
    pub const fn supports_concurrent_queries(self) -> bool {
        !matches!(
            self,
            ToolId::GhCloneRepo | ToolId::AstRewrite | ToolId::Clasify
        )
    }

    /// Config key whose value gates this tool (`None`: only `tools.enabled` /
    /// `tools.disabled`). Beta and family come from the contract; the clone and
    /// clasify gates are runtime prerequisites (persistent storage, a key).
    #[must_use]
    pub const fn availability_config_path(self) -> Option<&'static str> {
        if self.is_beta() {
            return Some("local.beta");
        }
        match self {
            ToolId::GhCloneRepo => Some("storage.mode"),
            ToolId::Clasify => Some("classification.api"),
            _ if self.is_local() => Some("local.enabled"),
            _ => None,
        }
    }

    /// Env vars bound to the gating config key, in config-contract order.
    #[must_use]
    pub fn availability_env_vars(self) -> Vec<&'static str> {
        let Some(path) = self.availability_config_path() else {
            return Vec::new();
        };
        crate::config::CONFIG_FIELDS
            .iter()
            .find(|field| field.path == path)
            .map(|field| field.env.iter().map(|binding| binding.name).collect())
            .unwrap_or_default()
    }
}

impl FromStr for ToolId {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        ToolId::from_name(value).ok_or(())
    }
}

impl std::fmt::Display for ToolId {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.as_str())
    }
}

/// The output channel of a follow-up call, classified by the core
/// contract's `continuationChannels`: `next` keeps pages, `hints` leads.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Channel {
    /// More of the same result.
    Page,
    /// An optional follow-up call.
    Lead,
}

/// The channel of continuation `name` emitted by `tool`. An entry named
/// after its own tool resumes that tool's walk (clasify's `next.clasify`);
/// the same name on another tool is a handoff lead.
#[must_use]
pub fn channel(tool: ToolId, name: &str) -> Channel {
    let name = kind(name);
    let page = name == tool.as_str()
        || continuation_channels::PAGE_NAMES.contains(&name)
        || has_prefix(name, continuation_channels::PAGE_PREFIXES);
    if page { Channel::Page } else { Channel::Lead }
}

/// The kind of continuation `name`: a name ending in digits repeats its
/// kind (`readHits2` is another `readHits`).
pub(crate) fn kind(name: &str) -> &str {
    let base = name.trim_end_matches(|c: char| c.is_ascii_digit());
    if base.is_empty() { name } else { base }
}

/// A page that leaves more of this result to read (a restart page starts
/// over instead): a row offering one is partial, and the CLI exits 6.
#[must_use]
pub fn is_remaining(tool: ToolId, name: &str) -> bool {
    channel(tool, name) == Channel::Page && !is_restart(name)
}

/// A page that starts the result over on the current source.
#[must_use]
pub fn is_restart(name: &str) -> bool {
    has_prefix(name, continuation_channels::RESTART_PREFIXES)
}

/// A page that continues after the evidence a row shows: following it from
/// an earlier part of a split row would skip the parts between, so it rides
/// the row's last part.
#[must_use]
pub fn resumes_after_shown(name: &str) -> bool {
    has_prefix(name, continuation_channels::RESUME_PREFIXES)
}

/// `name` is a prefix or a prefix followed by a capitalized word.
fn has_prefix(name: &str, prefixes: &[&str]) -> bool {
    prefixes.iter().any(|prefix| {
        name.strip_prefix(prefix).is_some_and(|rest| {
            rest.is_empty() || rest.starts_with(|c: char| c.is_ascii_uppercase())
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// GitHub routing sees exactly the contract's `github` family.
    #[test]
    fn the_github_identity_covers_exactly_the_github_family() {
        for id in ToolId::ALL {
            assert_eq!(id.github().is_some(), id.is_github(), "{}", id.as_str());
        }
    }

    fn contract_tools() -> &'static [serde_json::Value] {
        crate::contracts::parsed_contract().expect("contract")["tools"]
            .as_array()
            .expect("tools[]")
    }

    #[test]
    fn names_round_trip_and_are_unique() {
        let mut seen = std::collections::HashSet::new();
        for id in ToolId::ALL {
            assert!(seen.insert(id.as_str()), "duplicate name {}", id.as_str());
            assert_eq!(ToolId::from_name(id.as_str()), Some(id));
            assert_eq!(id.as_str().parse::<ToolId>(), Ok(id));
        }
        assert_eq!(ToolId::from_name("nope"), None);
        assert!("nope".parse::<ToolId>().is_err());
        assert_eq!(ToolId::from_name("semanticAssess"), None);
    }

    #[test]
    fn identity_and_policy_match_the_embedded_contract() {
        let tools = contract_tools();
        assert_eq!(tools.len(), ToolId::ALL.len());
        for (tool, id) in tools.iter().zip(ToolId::ALL) {
            assert_eq!(tool["name"], id.as_str());
            let family = match id.family() {
                ToolFamily::Local => "local",
                ToolFamily::GitHub => "github",
                ToolFamily::Remote => "remote",
            };
            assert_eq!(tool["family"], family, "{id}");
            assert_eq!(tool["cliOnly"], id.is_cli_only(), "{id}");
            assert_eq!(tool["beta"], id.is_beta(), "{id}");
            assert_eq!(tool["shortDescription"], id.short_description(), "{id}");
            assert_eq!(
                crate::contracts::tool_contract(id).expect("tool contract"),
                tool,
                "{id}"
            );
        }
    }

    #[test]
    fn every_gated_tool_resolves_env_vars_from_the_config_contract() {
        for id in ToolId::ALL {
            let vars = id.availability_env_vars();
            assert_eq!(
                vars.is_empty(),
                id.availability_config_path().is_none(),
                "{id}: {vars:?}"
            );
            if id.is_beta() {
                assert!(vars.contains(&"OCTOCODE_BETA"), "{id}: {vars:?}");
            }
        }
        assert!(
            ToolId::Clasify
                .availability_env_vars()
                .contains(&"OCTOCODE_JEV_KEY")
        );
    }
}
