import { AwarenessQueryResult, AwarenessQueryRow } from './repo-model.js';
import { summarize } from './repo-formats.js';
import { rowFiles } from './repo-files.js';
import { localPathFromReference } from './repo-scope.js';

export function renderRepoAgentsMd(all: AwarenessQueryResult): string {
  const sections = all.sections ?? {};
  const profile = sections['repo-profile']?.rows ?? [];
  const counts = Object.fromEntries(profile.map(row => [String(row['metric']), row['count'] ?? 0]));
  const promotable = (row: AwarenessQueryRow): boolean => Number(row['missing_reference_count'] ?? 0) === 0;
  const gotchas = (sections['gotchas']?.rows ?? []).filter(promotable).slice(0, 5);
  const lessons = (sections['lessons']?.rows ?? []).filter(promotable).slice(0, 5);
  const projectionWarnings = [
    Number(counts['missing_file_refs'] ?? 0) > 0 ? `Missing/stale file refs (${counts['missing_file_refs']}) — use \`query files --format table\` before trusting Refs/Missing refs lines.` : null,
    Number(counts['active_memories'] ?? 0) > 200 ? `Active memories high (${counts['active_memories']}) — prefer recall/CSV over full Markdown.` : null,
    Number(counts['tasks'] ?? 0) > 500 ? `Task history high (${counts['tasks']}) — use \`query workboard\`.` : null,
    Number(counts['all_open_refinements'] ?? 0) > 40 ? `All open refinements high (${counts['all_open_refinements']}) — inspect actionable, handoff, and instruction queues separately.` : null,
  ].filter((item): item is string => Boolean(item));
  const lines = [
    '# Octocode Awareness Map',
    '',
    '<!-- Generated by `octocode-awareness repo inject`. Regenerate instead of hand-editing. -->',
    '',
    'Digested awareness entrypoint. Root `AGENTS.md` should point here. SQLite is canonical; this folder is a capped wiki.',
    '',
    '## How To Use',
    '',
    '- Live: `octocode-awareness attend --workspace <repo> --compact`; use targeted `work list`, `query workboard`, `memory recall`, or `workspace status` commands with the same workspace.',
    '- Wiki leads below are projections, not proof. If root `AGENTS.md` lacks this pointer, use the source guidance and ask before editing root `AGENTS.md` unless already authorized.',
    '',
    '## Snapshot',
    '',
    `- Memories ${counts['active_memories'] ?? 0} · Gotchas ${counts['gotchas'] ?? 0} · Lessons ${counts['lessons'] ?? 0} · MissingFiles ${counts['missing_file_refs'] ?? 0} · Locks ${counts['active_locks'] ?? 0} · ActionableRefinements ${counts['actionable_refinements'] ?? 0} · AllOpenRefinements ${counts['all_open_refinements'] ?? 0} · Signals ${counts['open_signals'] ?? 0} · DevReview ${counts['developer_review'] ?? 0}`,
    '',
    '## Retro Files Map',
    '',
    'Generated retrospective projections in this folder (SQLite is canonical; regenerate, don\'t hand-edit). File work, locks, signals, and tasks live only in the DB — use live `attend`, `work`, or `query`.',
    '',
    '- Gotchas → `.octocode/GOTCHAS.md` · live `query gotchas` / `memory recall`',
    '- Lessons → `.octocode/LEARN.md` · live `query lessons`',
    '- Memory index → `.octocode/MEMORY.md` · live `memory recall --smart`',
    '- Bookmarks (external URLs/repos/docs only) → `.octocode/BOOKMARKS.md` · Local file refs/missing → live `query files` or `awareness/csv/files.csv` · Workboard → live `query workboard`',
    '- Developer review → `.octocode/DEVELOPER_REVIEW.md` · live `reflect developer-review` — agent feedback on the instructions themselves',
    '',
    '## Read Before Editing',
    '',
    '- Run `attend`, then inspect `FilesUnderWork` before editing. Record ordinary work with `work start`; overlap is allowed and visible.',
    '- Exclusive locks are reserved for sensitive files. An active exclusive lock blocks conflicting work.',
    '- Use targeted `memory recall --query <task> --smart --compact`; open one matching wiki lead only when live SQLite is unavailable, `attend.next` routes there, or projection history matters.',
    '- Prefer live `attend` / `work list` / `query` when freshness matters; run `repo inject` only when file readers need a fresh snapshot.',
    '',
    '## Projection Health',
    '',
    '- Canonical DB: `~/.octocode/memory/awareness.sqlite3`. Manifest: `.octocode/awareness/manifest.json`.',
    ...projectionWarnings.map(warning => `- ${warning}`),
    '',
  ];

  if (gotchas.length > 0) {
    lines.push('## Top Gotchas', '');
    for (const row of gotchas) lines.push(`- [${row['importance']}] ${summarize(String(row['observation']), 140)}`);
    lines.push('');
  }

  if (lessons.length > 0) {
    lines.push('## Top Lessons', '');
    for (const row of lessons) lines.push(`- [${row['label']}:${row['importance']}] ${summarize(String(row['observation']), 140)}`);
    lines.push('');
  }

  lines.push('## References', '');
  lines.push('- `.octocode/MEMORY.md` · `.octocode/GOTCHAS.md` · `.octocode/LEARN.md` · `.octocode/BOOKMARKS.md` · `.octocode/DEVELOPER_REVIEW.md`');
  lines.push('- `.octocode/awareness/manifest.json` · `.octocode/references/`');
  lines.push('');
  return lines.join('\n');
}

export function renderRowsDoc(title: string, rows: AwarenessQueryRow[], description: string, maxLines?: number, totalCount = rows.length): string {
  // Prefer higher-importance rows when a line budget forces omission.
  const ranked = [...rows].sort((a, b) => {
    const imp = Number(b['importance'] ?? 0) - Number(a['importance'] ?? 0);
    if (imp !== 0) return imp;
    return String(a['memory_id'] ?? a['plan_id'] ?? a['task_id'] ?? a['run_id'] ?? '')
      .localeCompare(String(b['memory_id'] ?? b['plan_id'] ?? b['task_id'] ?? b['run_id'] ?? ''));
  });
  const normalizedTotal = Number.isFinite(totalCount)
    ? Math.max(rows.length, Math.trunc(totalCount))
    : rows.length;
  const notSelected = Math.max(0, normalizedTotal - rows.length);
  const lines = [
    `# ${title}`,
    '',
    '<!-- Generated by `octocode-awareness repo inject`. Regenerate instead of hand-editing. -->',
    '',
    description,
    '',
    '',
    '',
  ];
  let omitted = 0;
  for (const row of ranked) {
    const id = String(row['memory_id'] ?? row['refinement_id'] ?? row['plan_id'] ?? row['task_id'] ?? row['run_id'] ?? row['signal_id'] ?? row['file_path'] ?? 'item');
    const label = row['label'] ? `[${row['label']}:${row['importance'] ?? ''}] ` : '';
    const titleText = row['task_context'] ?? row['subject'] ?? row['remember'] ?? row['name'] ?? row['title'] ?? row['rationale'] ?? row['file_path'] ?? id;
    const block = [`## ${label}${summarize(String(titleText), 100)}`];
    if (row['observation']) block.push('', summarize(String(row['observation']), 500));
    if (row['failure_signature']) block.push('', `Failure signature: \`${row['failure_signature']}\``);
    const refs = Array.isArray(row['references']) ? row['references'] as string[] : [];
    if (refs.length > 0) block.push('', `Refs: ${refs.join(', ')}`);
    const missingRefs = Array.isArray(row['missing_references']) ? row['missing_references'] as string[] : [];
    if (missingRefs.length > 0) block.push('', `Missing refs: ${missingRefs.join(', ')}`);
    block.push('', `Source id: \`${id}\``, '');
    const reserve = maxLines && (notSelected > 0 || rows.length > 0) ? 3 : 0;
    if (maxLines && lines.length + block.length + reserve > maxLines) {
      omitted++;
      continue;
    }
    lines.push(...block);
  }
  const shown = rows.length - omitted;
  const totalOmitted = normalizedTotal - shown;
  lines[6] = `Total: ${normalizedTotal} · Shown: ${shown} · Omitted: ${totalOmitted}`;
  if (totalOmitted > 0) {
    const detail = omitted > 0
      ? `Omitted by projection cap: ${omitted}. Not selected for Markdown: ${notSelected}.`
      : `Not selected for Markdown: ${notSelected}.`;
    const note = `${detail} Use CSV/HTML/query views for full rows.`;
    if (!maxLines || lines.length + 2 <= maxLines) lines.push(note, '');
  }
  return lines.join('\n');
}

/** True for any reference resolvable to a filesystem path (absolute, relative, `file:`/`path:` prefixed). */
export function isLocalFileReference(reference: string): boolean {
  return localPathFromReference(reference, null) !== null;
}

export function bookmarkKind(reference: string): string {
  const lower = reference.toLowerCase();
  if (/^(github|gh|repo):/.test(lower) || lower.includes('github.com/')) return 'Repos';
  if (/^https?:\/\//.test(lower)) return 'URLs';
  if (isLocalFileReference(reference)) return 'Files';
  if (/^(doc|docs|paper|book|resource|skill):/.test(lower)) return 'Docs';
  if (/^[a-z][a-z0-9+.-]*:/.test(lower)) return 'URIs';
  return 'Other';
}

/**
 * External-only resource index. Local file paths vary per checkout/machine and go
 * stale as code moves — they are already tracked via `query files` / GOTCHAS+LEARN+MEMORY
 * "Refs:"/"Missing refs:" lines / `awareness/csv/files.csv`, so they are excluded here
 * to keep bookmarks durable and portable across agents and clones.
 */
export function renderBookmarksDoc(memoryRows: AwarenessQueryRow[]): string {
  const byRef = new Map<string, { kind: string; sourceIds: string[]; labels: string[]; titles: string[]; missing: boolean }>();
  for (const row of memoryRows) {
    const refs = Array.isArray(row['references']) ? row['references'] as string[] : [];
    const missingRefs = new Set(Array.isArray(row['missing_references']) ? row['missing_references'] as string[] : []);
    const sourceId = String(row['memory_id'] ?? 'memory');
    const label = `${row['label'] ?? 'MEMORY'}:${row['importance'] ?? ''}`.replace(/:$/, '');
    const title = summarize(String(row['task_context'] ?? row['observation'] ?? sourceId), 90);
    for (const rawRef of refs) {
      const ref = rawRef.trim();
      if (!ref || isLocalFileReference(ref)) continue;
      const entry = byRef.get(ref) ?? { kind: bookmarkKind(ref), sourceIds: [], labels: [], titles: [], missing: false };
      if (!entry.sourceIds.includes(sourceId)) entry.sourceIds.push(sourceId);
      if (!entry.labels.includes(label)) entry.labels.push(label);
      if (!entry.titles.includes(title)) entry.titles.push(title);
      entry.missing = entry.missing || missingRefs.has(ref);
      byRef.set(ref, entry);
    }
  }

  const entries = [...byRef.entries()]
    .sort((a, b) => (
      a[1].kind.localeCompare(b[1].kind)
      || b[1].sourceIds.length - a[1].sourceIds.length
      || a[0].localeCompare(b[0])
    ))
    .slice(0, 80);
  const omitted = Math.max(0, byRef.size - entries.length);
  const lines = [
    '# Bookmarks',
    '',
    '<!-- Generated by `octocode-awareness repo inject`. Regenerate instead of hand-editing. -->',
    '',
    'External learnable resource leads from awareness memory references: URLs, GitHub repos, docs, papers, skills, and other network URIs.',
    'Local file paths are intentionally excluded — they vary per checkout/machine and go stale; use `query files`, `awareness/csv/files.csv`, or the Refs/Missing refs lines in GOTCHAS/LEARN/MEMORY instead.',
    'SQLite remains canonical; verify each bookmark against current source or primary material before relying on it.',
    '',
    `Count: ${byRef.size}`,
    omitted > 0 ? `Omitted by cap: ${omitted}` : null,
    '',
  ].filter((line): line is string => line !== null);

  let currentKind = '';
  for (const [ref, entry] of entries) {
    if (entry.kind !== currentKind) {
      currentKind = entry.kind;
      lines.push(`## ${currentKind}`, '');
    }
    const sourceText = entry.sourceIds.slice(0, 3).join(', ');
    const titleText = entry.titles.slice(0, 2).join(' | ');
    const labelText = entry.labels.slice(0, 3).join(', ');
    const health = entry.missing ? ' [missing file]' : '';
    lines.push(`- \`${ref}\`${health} - ${labelText}; source: ${sourceText}; ${titleText}`);
  }
  lines.push('');
  return lines.join('\n');
}

export function renderDeveloperReviewDoc(rows: AwarenessQueryRow[], maxLines: number): string {
  const open = rows.filter(row => String(row['state']) !== 'done');
  const resolved = rows.filter(row => String(row['state']) === 'done');
  const lines = [
    '# Developer Review',
    '',
    '<!-- Generated by `octocode-awareness repo inject`. Regenerate instead of hand-editing. -->',
    '',
    'Feedback from agents to the human who authors this repo\'s agent instructions',
    '(root `AGENTS.md`, `.octocode/AGENTS.md`, SKILL.md, system prompt, task briefs).',
    'Each item is where the *instructions* — not the code, not the harness — were ambiguous,',
    'wrong, over-constraining, or missing context. Recorded via `reflect record --fix-instructions`.',
    '',
    `Open: ${open.length} · Resolved: ${resolved.length}`,
    '',
  ];

  if (rows.length === 0) {
    lines.push(
      'No instruction feedback yet.',
      '',
      'Agents: when your instructions cost you time or a wrong turn, record it:',
      '`octocode-awareness reflect record --outcome partial --task "<what you did>" \\',
      '  --fix-instructions "<what the instructions should have said>"`',
      '',
    );
    return lines.join('\n');
  }

  function renderSection(title: string, sectionRows: AwarenessQueryRow[]): void {
    if (sectionRows.length === 0) return;
    lines.push(`## ${title} (${sectionRows.length})`, '');
    for (const row of sectionRows) {
      const source = String(row['source']);
      const state = String(row['state']);
      const agent = String(row['agent_id'] ?? 'agent');
      const files = rowFiles(row);
      const block = [`- ${summarize(String(row['feedback']), 240)}`];
      const meta = [`from ${agent}`, `via ${source}${state && state !== 'recorded' ? `:${state}` : ''}`, `id \`${row['id']}\``];
      if (files.length > 0) meta.push(`files: ${files.slice(0, 3).join(', ')}${files.length > 3 ? ` +${files.length - 3}` : ''}`);
      block.push(`  - ${meta.join(' · ')}`);
      if (maxLines && lines.length + block.length + 1 > maxLines) {
        lines.push(`- …more omitted by projection cap. Use \`query developer-review\` or \`reflect developer-review\`.`, '');
        return;
      }
      lines.push(...block);
    }
    lines.push('');
  }

  renderSection('Open', open);
  renderSection('Resolved', resolved);
  return lines.join('\n');
}

export function renderReferenceDoc(title: string, bullets: string[], rows: AwarenessQueryRow[] = []): string {
  const lines = [
    `# ${title}`,
    '',
    '<!-- Generated by `octocode-awareness repo inject`. Regenerate instead of hand-editing. -->',
    '',
    ...bullets.map(item => `- ${item}`),
    '',
  ];
  if (rows.length > 0) {
    lines.push('## Top Rows', '');
    for (const row of rows.slice(0, 25)) {
      const primary = row['file_path'] ?? row['title'] ?? row['metric'] ?? JSON.stringify(row);
      lines.push(`- ${primary}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
