#!/usr/bin/env node
/**
 * @octocodeai/octocode-awareness build script.
 *
 * Builds directly to out/ (no atomic staging).
 * Package-owned esbuild settings keep builds independent of the host repository.
 * Run `yarn typecheck` for a type-only check without rebuilding.
 */
import * as esbuild from 'esbuild';
import { execFileSync } from 'node:child_process';
import {
  chmodSync, cpSync, existsSync, mkdirSync,
  readFileSync, readdirSync, rmSync, writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { baseOptions } from './build-options.mjs';
import { coreEntryPoints, skillScriptEntries } from './build.entries.mjs';

const packageRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot    = resolve(packageRoot, '../..');
const outDir      = join(packageRoot, 'out');
const skillScriptsOutDir = join(outDir, 'skill-scripts');

// Awareness owns and publishes its skill alongside the CLI.
const packageSkillsRoot = join(packageRoot, 'skills');
const skillSources = [
  { name: 'octocode-awareness', source: join(packageSkillsRoot, 'octocode-awareness') },
];
const agentSkillsRoot = join(repoRoot, '.agents', 'skills');
const tscBin = createRequire(import.meta.url).resolve('typescript/bin/tsc');

// ── Shebang + chmod helpers ───────────────────────────────────────────────────

const warningGuard = [
  '#!/usr/bin/env node',
  "process.removeAllListeners('warning');",
  "process.on('warning', (w) => {",
  "  if (w?.name === 'ExperimentalWarning' && String(w?.message).includes('SQLite')) return;",
  '  console.error(w?.stack ?? String(w));',
  '});',
].join('\n');

const generatedNote =
  '// @generated by packages/octocode-awareness/build.mjs — do not edit; run `yarn build` to refresh.';

function makeExecutable(filePath, banner = '#!/usr/bin/env node') {
  const src = readFileSync(filePath, 'utf8');
  writeFileSync(filePath, `${banner}\n${src.replace(/^#![^\n]*\n?/, '')}`);
  chmodSync(filePath, 0o755);
}

// ── Clean ─────────────────────────────────────────────────────────────────────

process.chdir(packageRoot);
rmSync(outDir, { recursive: true, force: true });
rmSync(join(packageRoot, 'dist'), { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

// ── Core bundle (code-split) ──────────────────────────────────────────────────

await esbuild.build({
  ...baseOptions,
  entryPoints:  coreEntryPoints,
  outdir:       outDir,
  entryNames:   '[name]',
  chunkNames:   'chunks/[name]-[hash]',
  splitting:    true,
  minify:       true,
});

// ── Skill-script standalone bundles (no shared chunks) ────────────────────────

mkdirSync(skillScriptsOutDir, { recursive: true });
await Promise.all(
  skillScriptEntries.map(({ entryPoints, outfileName }) =>
    esbuild.build({
      ...baseOptions,
      entryPoints,
      outfile: join(skillScriptsOutDir, outfileName),
      minify:  true,
    }),
  ),
);

// ── Type declarations (tsc --emitDeclarationOnly → out/types/) ────────────────

execFileSync(
  process.execPath,
  [tscBin, '--emitDeclarationOnly', '--outDir', join(outDir, 'types'), '-p', 'tsconfig.build.json'],
  { cwd: packageRoot, stdio: 'inherit' },
);

// ── Shebangs + chmod ──────────────────────────────────────────────────────────

for (const name of ['octocode-awareness.js', 'hook-runner.js']) {
  makeExecutable(join(outDir, name), warningGuard);
}
for (const name of ['extract-hook-files.js']) {
  makeExecutable(join(outDir, name));
}
for (const name of ['awareness.mjs', 'hook-runner.mjs']) {
  makeExecutable(join(skillScriptsOutDir, name), `${warningGuard}\n${generatedNote}`);
}
makeExecutable(join(skillScriptsOutDir, 'extract-hook-files.mjs'), `#!/usr/bin/env node\n${generatedNote}`);

// ── Static assets ─────────────────────────────────────────────────────────────

cpSync(join(packageRoot, 'docs'),   join(outDir, 'docs'),   { recursive: true });
cpSync(join(packageRoot, 'assets'), join(outDir, 'assets'), { recursive: true });

// ── Skills ────────────────────────────────────────────────────────────────────

const generatedScripts = ['awareness.mjs', 'hook-runner.mjs', 'extract-hook-files.mjs'];
const awarenessScripts = join(packageSkillsRoot, 'octocode-awareness', 'scripts');
for (const { source } of skillSources) {
  if (!existsSync(join(source, 'SKILL.md'))) throw new Error(`Missing skill source: ${source}`);
}

// Refresh generated helpers before copying, so each mirror is current in one build.
for (const name of generatedScripts) {
  cpSync(join(skillScriptsOutDir, name), join(awarenessScripts, name));
}

const packagedSkillsRoot = join(outDir, 'skills');
const filter = (path) => !path.split(/[\\/]/).some((part) =>
  ['node_modules', '.octocode', '.DS_Store', 'octocode-config.mjs'].includes(part));
for (const { name, source } of skillSources) {
  const destinations = [join(packagedSkillsRoot, name), join(agentSkillsRoot, name)];
  for (const destination of destinations) {
    rmSync(destination, { recursive: true, force: true });
    cpSync(source, destination, { recursive: true, filter });
  }
}

// ── Summary ───────────────────────────────────────────────────────────────────

const chunkCount = readdirSync(join(outDir, 'chunks')).length;
console.log('✓ @octocodeai/octocode-awareness built → out/');
console.log(`✓ Awareness CLI → out/octocode-awareness.js (${chunkCount} shared chunks)`);
console.log('✓ schemas served dynamically by the CLI (no static schema files)');
console.log(`✓ bundled skills → out/skills/ (${skillSources.map(({ name }) => name).join(', ')})`);
