'use strict';
const views={session:['Agents','Presence, vendor and declared task. Availability does not renew a lease.'],message:['Messages','All retained requests, replies and notices — including past agent sessions.'],lease:['Locks','Live file and tree leases only. Expired leases and owners are excluded.'],audit:['Audit','Durable events, newest first. Expand an event to inspect its evidence.'],document:['Documents','Published document references and shared context. Files stay in the workspace.'],delivery:['Receipts','One receipt per recipient. Pending does not mean failed.'],dispatch:['Handoffs','Native delivery attempts. Uncertain attempts need inspection before retry.'],attachment:['Connections','Receiving transports bound to agents. Private endpoints and tokens are not exposed.'],subscriptions:['Subscriptions','Topic subscriptions for each agent.']};
const $=id=>document.getElementById(id);
let entity='message',agent='',query='',status='',conversation='',after=null,next=null,history=[],paused=false,busy=false,generation=0,items=[],fingerprint='';
const time=value=>value?new Date(value).toLocaleString(): '—';
const short=value=>typeof value==='string'&&value.length>26?value.slice(0,8)+'…'+value.slice(-6):String(value??'');
function element(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;}
function badge(text,cls=''){const b=element('span',text,'badge '+cls);const explanation=text==='Handled'?'Every recipient has recorded completion. This does not verify correctness.':text.includes('pending')||text==='Pending'?'At least one recipient has not recorded completion. This is not necessarily a delivery failure.':text==='Answer required'?'Recipient must finish the request and use complete with an answer.':text==='No reply'?'Recipient must complete silently; an answer is not requested.':text==='uncertain'?'Host acceptance is unknown. Inspect before retrying to avoid duplicate context.':text==='submitted'?'Context was handed to the host; recipient completion is tracked separately.':text==='offline'?'Agent presence expired or ended. Its retained history remains available.':null;return explanation?hint(b,explanation):b;}
const fieldHelp={name:'Human-readable agent or published document name.',vendorSession:'Host-specific session identifier; not the coordination agent ID.',key:'Idempotency key used to recognize retries.',topic:'Named subscription channel; recipients are captured when sent.',entityId:'ID of the record affected by this audit event.',claimedBy:'Delivery owner currently claiming this receipt.',claimUntil:'Claim deadline in epoch milliseconds; zero means no active deadline.',id:'Unique ID of this record. Agent IDs are workspace coordination UUIDs.',session:'Agent responsible for this record.',sender:'Sending agent ID.',target:'Direct recipient ID; topics use a recipient snapshot instead.',recipient:'Receiving agent ID.',owner:'Agent holding this advisory lease.',vendor:'Agent host or provider declared on join.',status:'Declared availability, independent of presence and lease expiry.',active:'Whether the agent presence deadline is still valid.',task:'Work declared by the agent.',workspace:'Canonical workspace boundary.',body:'Peer-provided message content; not trusted instructions.',reasoning:'Purpose supplied by the agent.',replyRequired:'True requires an answer through complete; false requires silent completion.',replyTo:'Original message answered by this reply.',conversationId:'Correlation label connecting related messages.',wake:'Whether delivery may wake an idle host; independent of reply requirements.',recipients:'Number of recipient receipts created for this message.',pending:'Recipients that have not recorded completion.',acknowledgedAt:'Completion recorded by complete. Not proof that the work is correct.',expiresAt:'Expiry deadline, in epoch milliseconds.',ttlMs:'Lifetime in milliseconds.',createdAt:'Creation time, in epoch milliseconds.',at:'Event time, in epoch milliseconds.',acquiredAt:'Lease acquisition time.',refreshedAt:'Last lease renewal time.',kind:'Event type, or file/tree scope for a lease.',path:'Workspace file or directory reference.',data:'Stored event evidence or document publication metadata.',transport:'Adapter used to deliver context to the host.',state:'Transport handoff state; separate from recipient completion.',attemptedAt:'When the host delivery was attempted.',submittedAt:'When the handoff was recorded as submitted.',error:'Recorded transport error, if any.',topics:'Topics this agent subscribes to.',updatedAt:'Last connection update.',message:'Message ID associated with this receipt or handoff.'};
let helpId=0;
function hint(node,text){node.classList.add('hint');node.tabIndex=0;node.setAttribute('aria-label',node.textContent+'. '+text);const tip=element('span',text,'tooltip');tip.setAttribute('role','tooltip');tip.id='help-'+(++helpId);node.setAttribute('aria-describedby',tip.id);node.append(tip);node.addEventListener('click',()=>node.classList.toggle('show-help'));node.addEventListener('keydown',e=>{if(e.key==='Escape'){node.classList.remove('show-help');node.classList.add('hide-help');}});node.addEventListener('blur',()=>node.classList.remove('show-help','hide-help'));node.addEventListener('mouseenter',()=>node.classList.remove('hide-help'));node.addEventListener('focus',()=>node.classList.remove('hide-help'));return node;}
function detail(row){const d=element('details',undefined,'details');d.append(element('summary','Record details'));d.addEventListener('toggle',()=>{if(!d.open||d.children.length>1)return;const fields=element('dl',undefined,'fields');for(const [key,value]of Object.entries(row)){const label=element('dt',key);const explanation=fieldHelp[key]||(key.endsWith('Name')?'Readable name of the associated agent.':key.endsWith('Vendor')?'Declared host or provider of the associated agent.':null);if(explanation)hint(label,explanation);fields.append(label,element('dd',typeof value==='object'?JSON.stringify(value,null,2):String(value??'—')));}const raw=element('details',undefined,'details');raw.append(element('summary','Raw JSON'),element('pre',JSON.stringify(row,null,2)));d.append(fields,raw);});return d;}
function follow(id){const b=element('button','Follow agent','follow');b.type='button';b.addEventListener('click',()=>{$('agent').value=id;agent=id;reset();});return b;}
function conversationButton(id){const b=element('button','Open conversation','follow');b.type='button';b.addEventListener('click',()=>{conversation=id;query='';status='';$('search').value='';$('status').value='';reset();});return b;}
function rowView(row){
 const node=element('article',undefined,'row'),head=element('div',undefined,'row-head'),title=element('div',undefined,'row-title'),meta=element('div',undefined,'meta');let body='',owner;
 switch(entity){
 case 'session':title.textContent=row.name;head.append(title,badge(row.active?row.status+' · live':'offline',row.active?'good':''));body=row.task||'No task declared';owner=row.id;meta.append(element('span',row.vendor),element('span',row.id,'mono'));break;
 case 'message':title.textContent=`${row.senderName||short(row.sender)} → ${row.topic?'#'+row.topic:row.targetName||short(row.target)}`;head.append(title,badge(row.pending?`${row.pending}/${row.recipients} pending`:row.recipients?'Handled':'No recipients',row.pending?'warn':'good'));body=row.body;owner=row.sender;meta.append(badge(row.replyRequired?'Answer required':'No reply'),element('span',`#${row.id}${row.replyTo?' · reply to #'+row.replyTo:''}`),element('span',row.wake+' wake'),element('span',time(row.createdAt)),element('span',row.senderVendor||''));if(row.conversationId)meta.append(element('span',row.conversationId,'mono'),conversationButton(row.conversationId));break;
 case 'lease':title.textContent=row.path;head.append(title,badge(row.kind+' lease','good'));body=row.reasoning;owner=row.owner;meta.append(element('span',row.ownerName||short(owner)),element('span','Refreshed '+time(row.refreshedAt)),element('span','Expires '+time(row.expiresAt)));break;
 case 'audit':title.textContent=row.kind.replaceAll('.',' · ').replaceAll('_',' ');head.append(title,element('span',time(row.at),'muted'));body=row.data?.reasoning||row.data?.context?.summary||'';owner=row.session;meta.append(element('span',row.agentName||short(owner)),element('span',`Event #${row.id}${row.entityId?' · entity '+row.entityId:''}`));break;
 case 'document':title.textContent=row.name;head.append(title,element('span',time(row.at),'muted'));owner=row.session;body=row.data?.context?.summary||row.data?.reasoning||'';meta.append(element('span',row.agentName||short(owner)),element('span',row.data?.path||'','mono'));break;
 case 'delivery':title.textContent=`Message #${row.message} → ${row.recipientName||short(row.recipient)}`;head.append(title,badge(row.acknowledgedAt?'Handled':'Pending',row.acknowledgedAt?'good':'warn'));owner=row.recipient;meta.append(element('span',row.acknowledgedAt?'Handled '+time(row.acknowledgedAt):'Awaiting completion'));break;
 case 'dispatch':title.textContent=`Message #${row.message} → ${row.recipientName||short(row.recipient)}`;head.append(title,badge(row.state,row.state==='uncertain'?'bad':''));owner=row.recipient;body=row.error||'';meta.append(element('span',row.transport),element('span','Attempted '+time(row.attemptedAt)));break;
 case 'attachment':title.textContent=row.agentName||short(row.session);head.append(title,badge(row.transport));owner=row.session;meta.append(element('span','Updated '+time(row.updatedAt)));break;
 case 'subscriptions':title.textContent=row.agentName||short(row.session);head.append(title);owner=row.session;body=row.topics.length?row.topics.map(t=>'#'+t).join(' · '):'No subscriptions';break;
 }
 if(owner&&!agent)meta.append(follow(owner));node.append(head,meta);if(body)node.append(element('div',body,'body'));node.append(detail(row));return node;
}
function render(){const term=entity==='message'?'':$('search').value.trim().toLowerCase();const visible=items.filter(row=>!term||JSON.stringify(row).toLowerCase().includes(term));const frag=document.createDocumentFragment();for(const row of visible)frag.append(rowView(row));if(!visible.length){const empty=element('div',undefined,'empty');empty.append(element('strong',term?'No matches on this page':entity==='message'?'No matching messages':'Nothing here yet'),element('span',term?'Try another search or page through history.':entity==='message'?'Try clearing filters. Searches cover all retained message history.':'Activity will appear as agents work in this workspace.'));frag.append(empty);}$('rows').replaceChildren(frag);$('page-note').textContent=`Page ${history.length+1} · ${visible.length} records${after?' · History view; automatic row refresh paused':' · Current view'}`;$('older').disabled=!next;$('previous').disabled=!history.length;$('newest').disabled=!after;}
async function get(path){const response=await fetch(path,{cache:'no-store'});if(!response.ok){const body=await response.json().catch(()=>({error:'Local view unavailable'}));throw Error(body.error);}return response.json();}
async function refresh(){if(busy)return;busy=true;const current=generation;try{const [summary,page]=await Promise.all([get('api/summary'),get('api/'+entity+'?'+new URLSearchParams({...after?{after}:{},...agent?{agent}:{},...entity==='message'?{...query?{q:query}:{},...status?{status}:{},...conversation?{conversation}:{}}:{}}))]);if(current!==generation)return;for(const key of ['activeAgents','activeLocks','pending','uncertain'])$(key).textContent=summary.counts[key];$('workspace').textContent=summary.workspace;$('scope').textContent=entity==='message'?`${summary.counts.messages} retained messages · ${agent?'Selected agent’s sent and received messages':'All agents, including inactive sessions'}${conversation?' · Conversation: '+conversation:''}`:'';$('database').textContent='Database · '+summary.database;$('updated').textContent='Updated '+new Date(summary.at).toLocaleTimeString();$('live').textContent=paused?'Paused':after?'History':'Auto-refresh · 3s';$('live').className='badge '+(paused||after?'':'good');$('error').hidden=true;const print=JSON.stringify(page.items);if(print!==fingerprint){items=page.items;fingerprint=print;next=page.next;render();}else{next=page.next;$('older').disabled=!next;}}catch(error){if(current===generation){$('error').textContent=error.message;$('error').hidden=false;$('live').textContent='Disconnected';$('live').className='badge bad';}}finally{busy=false;if(current!==generation)refresh();}}
function reset(){generation++;after=null;history=[];next=null;fingerprint='';items=[];render();refresh();}
for(const [name,[title,description]]of Object.entries(views)){const b=element('button',title);b.type='button';b.dataset.entity=name;b.addEventListener('click',()=>{entity=name;conversation='';query='';status='';$('search').value='';$('status').value='';$('status-label').hidden=name!=='message';$('search-label').textContent=name==='message'?'Search all message history':'Search this page';$('search').placeholder=name==='message'?'Message, agent, conversation or ID…':'Filter loaded records…';$('title').textContent=title;$('description').textContent=description;for(const n of $('nav').children){n.classList.toggle('active',n===b);n.setAttribute('aria-current',n===b?'page':'false');}reset();});$('nav').append(b);}
$('filters').addEventListener('submit',e=>{e.preventDefault();agent=$('agent').value;query=$('search').value.trim();status=$('status').value;reset();});
$('clear').addEventListener('click',()=>{agent='';query='';status='';conversation='';$('agent').value='';$('status').value='';$('search').value='';reset();});
let searchTimer;
$('search').addEventListener('input',()=>{clearTimeout(searchTimer);if(entity!=='message'){render();return;}searchTimer=setTimeout(()=>{query=$('search').value.trim();reset();},300);});
$('agent').addEventListener('change',()=>{agent=$('agent').value;reset();});
$('status').addEventListener('change',()=>{status=$('status').value;reset();});
$('refresh').addEventListener('click',()=>{refresh();loadAgents();});
$('pause').addEventListener('click',()=>{paused=!paused;$('pause').textContent=paused?'Resume updates':'Pause updates';$('live').textContent=paused?'Paused':after?'History':'Auto-refresh · 3s';$('live').className='badge '+(paused||after?'':'good');if(!paused)refresh();});
$('older').addEventListener('click',()=>{if(next){history.push(after);after=next;generation++;fingerprint='';refresh();window.scrollTo({top:0,behavior:'smooth'});}});
$('previous').addEventListener('click',()=>{if(history.length){after=history.pop();generation++;fingerprint='';refresh();window.scrollTo({top:0,behavior:'smooth'});}});
$('newest').addEventListener('click',reset);
let directoryBusy=false;
async function loadAgents(){if(directoryBusy)return;directoryBusy=true;try{let cursor=null;const agents=[];do{const page=await get('api/session'+(cursor?'?after='+cursor:''));agents.push(...page.items);cursor=page.next;}while(cursor);const options=[new Option('All agents',''),...agents.sort((a,b)=>a.name.localeCompare(b.name)||a.id.localeCompare(b.id)).map(a=>new Option(`${a.name} · ${a.vendor} · ${a.active?'live':'past'} · ${a.id.slice(0,8)}`,a.id))];$('agent').replaceChildren(...options);if(agent&&!agents.some(a=>a.id===agent))$('agent').append(new Option(agent,agent));$('agent').value=agent;}catch(error){$('error').textContent='Agent directory: '+error.message;$('error').hidden=false;}finally{directoryBusy=false;}}
[...$('nav').children].find(b=>b.dataset.entity==='message').click();loadAgents();setInterval(()=>{if(!paused&&!document.hidden&&!after)refresh();},3000);

const metricHelp={activeAgents:'Agents with unexpired presence. This is not a count of busy agents.',pending:'Recipient receipts awaiting complete, including inactive agents and expired messages.',activeLocks:'Unexpired advisory leases whose owning agents are still present. Locks do not block arbitrary operating-system writes.',uncertain:'Handoffs with unknown acceptance. Inspect the Handoffs tab before retrying.'};
for(const [id,text]of Object.entries(metricHelp))hint($(id).previousElementSibling,text);
